GSA/notifications-api

README.md
Updated QUICKSTART section with a little more info in spots.
Reformatted a bit because text wrap within code blocks can be kinda yuck.
=> Devdocs update

README.md
A couple edits in quickstart found while onboarding
=> Updates to quickstart while onboarding Carly

.github/workflows/checks.yml, app/aws/s3.py, app/cloudfoundry_config.py, app/config.py, manifest.yml, terraform/staging/main.tf, tests/app/aws/test_s3.py, tests/app/celery/test_ftp_update_tasks.py, tests/app/celery/test_nightly_tasks.py, tests/app/celery/test_research_mode_tasks.py, tests/app/celery/test_scheduled_tasks.py, tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py, tests/app/letters/test_letter_utils.py, tests/app/service/send_notification/test_send_pdf_letter_notification.py, tests/app/service/test_rest.py, tests/app/test_cloudfoundry_config.py
Create s3 buckets via cloud.gov managed services. This will ensure our bucket settings are compliant.
This should be merged before, but very near the related admin repo PR.
#62
=> Terraform s3 buckets

Pipfile, Pipfile.lock
Maybe this will make Cloud Foundry happy?
=> Add versions in pipfile for git deps

app/cloudfoundry_config.py, app/config.py, sample.env, tests/app/test_cloudfoundry_config.py
Also took the opportunity to replace directly accessing os.environ with the getenv function within config.py
=> Fix deployed db string

.github/workflows/deploy-demo.yml, .github/workflows/deploy.yml, .github/workflows/terraform-demo.yml, .github/workflows/terraform-production.yml, .github/workflows/terraform-staging.yml, app/config.py, deploy-config/demo.yml, deploy-config/production.yml, deploy-config/staging.yml, docs/deploying.md, manifest.yml, terraform/bootstrap/import.sh, terraform/bootstrap/main.tf, terraform/bootstrap/run.sh, terraform/bootstrap/teardown_creds.sh, terraform/bootstrap/variables.tf, terraform/create_service_account.sh, terraform/demo/main.tf, terraform/demo/providers.tf, terraform/demo/variables.tf, terraform/destroy_service_account.sh, terraform/production/main.tf, terraform/production/providers.tf, terraform/production/variables.tf, terraform/set_space_egress.sh, terraform/staging/main.tf, terraform/staging/providers.tf, terraform/staging/variables.tf
* Adds a demo environment to be deployed from `production` branch
* Sets up terraform for staging, demo, production
* Updates routes to not conflict with original 10x app
=> Set up studio cloud.gov environment

.github/actions/deploy-proxy/action.yml, .github/workflows/deploy-demo.yml, .github/workflows/deploy.yml, .profile, app/config.py, deploy-config/egress_proxy/notify-api-demo.allow.acl, deploy-config/egress_proxy/notify-api-staging.allow.acl, deploy-config/sandbox.yml, docs/deploying.md, manifest.yml, terraform/create_service_account.sh, terraform/sandbox/main.tf, terraform/sandbox/providers.tf, terraform/sandbox/variables.tf, terraform/shared/egress_space/main.tf, terraform/shared/egress_space/providers.tf, terraform/shared/egress_space/variables.tf, terraform/staging/main.tf
Updates:
* creates a sandbox space for easier ad-hoc testing of infrastructure code.
* Sets up a public-egress space for each app space, and deploys https://github.com/GSA/cg-egress-proxy there to control outbound traffic
TODO: Matching update to compliance repo for boundary updates and SC-7 docs
closes #108
=> Restricted space egress

README.md, docs/one-off-tasks.md, docs/queues-and-tasks.md
Just leaving some notes about our Celery setup.
This closes https://github.com/GSA/notifications-admin/pull/150
=> Add some docs about queues

Pipfile, Pipfile.lock, app/celery/scheduled_tasks.py, app/config.py, app/dao/notifications_dao.py, tests/app/celery/test_scheduled_tasks.py, tests/app/dao/notification_dao/test_notification_dao.py
Found while investigating https://github.com/GSA/notifications-admin/issues/150
The notifications_utils update corresponds to https://github.com/GSA/notifications-utils/pull/14
=> SMS provider cleanup

terraform/demo/main.tf, terraform/demo/providers.tf, terraform/production/main.tf, terraform/production/providers.tf, terraform/sandbox/main.tf, terraform/sandbox/providers.tf, terraform/shared/egress_space/main.tf, terraform/shared/egress_space/providers.tf, terraform/shared/egress_space/variables.tf, terraform/staging/main.tf, terraform/staging/providers.tf
Incorporate improvements to the shared terraform modules, and specify the version so that future improvements don't accidentally break our setup.
I expect that terraform plan should show no changes.
closes #154
=> Use versioned terraform modules

.github/workflows/checks.yml, .github/workflows/daily_checks.yml, .github/workflows/deploy-demo.yml, .github/workflows/deploy.yml, .profile, Makefile, Pipfile, Pipfile.lock, app/notifications/process_notifications.py, deploy-config/egress_proxy/notify-api-demo.allow.acl, deploy-config/egress_proxy/notify-api-staging.allow.acl, manifest.yml, newrelic.ini, sample.env, scripts/migrate_and_run_web.sh
Work towards #167 
Once we get new relic ingesting data from staging I'll scope out additional work to tweak what we're sending them and verifying that we're receiving expected events.
Open question: should we default to sending data to NR in development? Currently it does, and I think that's my preference until we get the integration solid, and then turn off for any local environments.
=> Initial setup of New relic

docs/infra-overview.md, newrelic.ini
=> Add onboarding step for new relic to infra-overview.md

migrations/versions/0392_drop_letter_permissions_.py
=> Drop send_letters permissions for existing users

README.md, sample.env
Just a couple doc updates after setting up the project from scratch.
=> Update docs for project setup

deploy-config/production.yml, deploy-config/sandbox.yml, docs/infra-overview.md, terraform/production/main.tf
* Enables SNS terraform once in production
* Sets the default from number for production and sandbox
* Documents the available prod phone numbers.
closes #38
=> Configure default SMS from-number in production

.github/workflows/deploy-demo.yml, .github/workflows/deploy.yml, deploy-config/egress_proxy/notify-api-demo.allow.acl
Incorporates #212 to bring demo infrastructure in line with baseline.
=> Demo deploy

.github/workflows/checks.yml, .github/workflows/daily_checks.yml, Makefile
Get pip-audit passing again until #217 can be worked on.
=> Ignore known issue with redis 4.5.3 (API)

.github/workflows/checks.yml, .github/workflows/daily_checks.yml, Makefile, Pipfile.lock
Updates all python dependencies
closes #217
=> Update dependencies (API)

tests/app/db.py
There doesn't appear to be any need for this to be a real endpoint.
=> Remove real endpoint from test suite

Pipfile.lock, app/config.py
=> Update utils to get logging improvements

.github/actions/deploy-proxy/action.yml, manifest.yml
=> Deploy app to cflinuxfs4 stack (API)

.github/workflows/checks.yml, .github/workflows/daily_checks.yml
The API side of https://github.com/GSA/notifications-admin/pull/498
=> Bump pip-audit action to 1.0.6

.github/workflows/deploy-prod.yml, .github/workflows/terraform-production.yml, deploy-config/egress_proxy/notify-api-production.allow.acl, deploy-config/egress_proxy/notify-api-production.deploy.acl, docs/deploying.md, docs/infra-overview.md, terraform/production/main.tf
This PR represents steps 1-3 of deploying the API app from infra-overview.
=> Enable production deploy workflows

app/notifications/sns_cert_validator.py
=> Fix SNS cert address regex to allow govcloud region domain

app/celery/research_mode_tasks.py, app/delivery/send_to_providers.py, app/models.py, tests/app/celery/test_provider_tasks.py, tests/app/celery/test_reporting_tasks.py, tests/app/celery/test_research_mode_tasks.py, tests/app/clients/test_sms.py, tests/app/dao/test_fact_billing_dao.py, tests/app/dao/test_jobs_dao.py, tests/app/dao/test_organisation_dao.py, tests/app/dao/test_provider_details_dao.py, tests/app/dao/test_services_dao.py, tests/app/dao/test_uploads_dao.py, tests/app/delivery/test_send_to_providers.py, tests/app/inbound_sms/test_rest.py, tests/app/notifications/test_notifications_ses_callback.py, tests/app/notifications/test_validators.py, tests/app/organisation/test_invite_rest.py, tests/app/organisation/test_rest.py, tests/app/performance_dashboard/test_rest.py, tests/app/service/send_notification/test_send_notification.py, tests/app/service/test_rest.py, tests/app/service_invite/test_service_invite_rest.py, tests/app/test_route_authentication.py, tests/app/user/test_rest.py, tests/app/user/test_rest_verify.py, tests/app/v2/notifications/test_post_notifications.py
https://github.com/orgs/GSA/projects/20/views/1?pane=issue&itemId=10024759
This PR reduces the number of skips from 120 to 34.  The remaining skips are more problematical and will take more time to resolve (inbound SMS, etc.)
=> notify-34 fix skipped tests

docs/adrs/README.md
This changeset reformats our Architecture Decision Log for Architecture Decision Records so a bit more information is displayed.  Now, instead of a list, they are in a table with the following details:
- ADR number
- Title
- Current Status
- Date Last Modified
- None
=> Updated Architecture Decision Log

.github/ISSUE_TEMPLATE/create-new-adr-form.yml, docs/adrs/0001-establishing-adrs-for-us-notify.md, docs/adrs/0002-how-to-handle-timezones.md, docs/adrs/0003-implementing-invite-expirations.md, docs/adrs/README.md
This changeset fixes a few lingering typos and incorrect information in the ADRs and updates them with some final decisions.  It also fixes an issue with the ADR creation form for GitHub.
- None
=> Fix issues and update ADRs

docs/adrs/README.md
This changeset updates our Architecture Decision Log (ADL) with ADR 0004:  Designing Pilot Content Visibility.
- None.
=> Update ADL to include ADR 0004

app/dao/notifications_dao.py
trying to see if the SQLAlchemy query will work without the mystery session synchronization flag before abandoning SQLAlchemy and going with pure sql.
=> try without weird SQLAlchemy flag

Pipfile, Pipfile.lock, app/config.py
Pick up the daily message limit from notification_utils.  Reset the pipfile to use the main branch for notification_utils after the PR in notification_utils is approved and merged.
=> notify-512: get daily message limit from notification_utils

migrations/versions/0397_rename_organisation_2.py
=> Rename organisation_types table

app/celery/tasks.py, app/notifications/process_notifications.py, app/notifications/validators.py, app/service/send_notification.py, tests/app/celery/test_tasks.py, tests/app/notifications/test_process_notification.py, tests/app/notifications/test_validators.py, tests/app/service/send_notification/test_send_one_off_notification.py
Redoing this PR from scratch.  Removing daily message limit from checks.
=> notify-api-340 remove daily message limit

terraform/demo/main.tf, terraform/staging/main.tf
I couldn't figure out how to unsubscribe from job notifications, so I figured I'd fix the scan instead :)
=> Remove Ryan from list of deployers for staging and demo egress spaces

.github/workflows/adr-accepted.yml
This will allow some troubleshooting upstream.
=> Switch branch of ADR action

.github/workflows/deploy-demo.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy.yml
This changeset adds the E2E test environment variables to our deployment scripts so that they are accessible to the application and database migrations.
- We need to be mindful of managing the secrets.
=> Add E2E test environment variables to deployments

app/clients/cloudwatch/aws_cloudwatch.py, app/commands.py, migrations/versions/0402_total_message_limit_default.py, tests/app/test_commands.py
For some mysterious reason, code coverage dropped to 94% with my trivial changes, so had to write another test.
=> notify-api-490 fix sns region

docs/adrs/0008-adr-handle-paid-quotas-at-the-organization-level.md
This should be ready now, based on recent discussions. Note that the next steps all need GitHub issues created.
=> Add ADR 0008: Handle paid quotas at the organization level

docs/all.md
This addresses https://github.com/GSA/notifications-admin/issues/864
=> Add new phone numbers to docs

docs/all.md
Content changes to add more specificity from our recent onboardings.
Closes #417
=> Update onboarding docs

app/dao/services_dao.py, app/models.py, app/service/rest.py, tests/app/conftest.py, tests/app/db.py, tests/app/service/test_rest.py
Reverting backend logic that removed the default sms sender.
=> Revert "Added flag to remove default sender from user list"

README.md
I update the readme file with notes that I picked up when I worked through the installation that could be more clear and helpful for others in the future.
=> Update Readme File 

docs/adrs/0005-agreement-data-model.md
Added a couple of clarifications to the Agreement model status field (active or expired status values, with a note about draft/pending possibly coming in the future).
- None for this change.
=> ADR 0005 - Agreement Data Model Updates

Makefile, README.md, sample.env
This changeset updates the README.md file with a set of entirely new instructions. These updates are intended to improve clarity, simplify steps, and reduce confusion and environment-setup gotchas that folks have run into previously and we have learned from.  A couple of other changes are also included:
- Minor adjustments to the Makefile to improve make bootstrap
- Updates to the sample.env file to include previously missing required environment variables
- Additional support for Python virtual environments
- Being mindful of not committing any secrets to the repository.
=> Update README with new instructions and improve setup

README.md, docs/all.md
This changeset makes a few more adjustments to the README.md file to account for updates in the other repos that are forthcoming.
- None with this change.
=> Minor README.md updates

README.md, docs/all.md
This changeset adds a bit of documentation to explain with the `.profile` file is used for with our application.
- Being mindful of the nature of the application configuration information.
=> Add `.profile` file information to docs

migrations/versions/0407_fix_preferred_timezone.py
=> Notify admin 931 fix preferred_timezone in db

docs/all.md
Edited production phone numbers to assign the ones in use to three pilot partners with live services.
=> Production phone number assignments

terraform/bootstrap/providers.tf, terraform/development/main.tf, terraform/development/providers.tf, terraform/sandbox/main.tf, terraform/sandbox/providers.tf, terraform/shared/egress_space/main.tf, terraform/shared/egress_space/providers.tf, terraform/shared/ses/main.tf, terraform/shared/ses/providers.tf, terraform/shared/ses/variables.tf, terraform/shared/sns/main.tf, terraform/shared/sns/providers.tf, terraform/shared/sns/variables.tf, terraform/staging/main.tf, terraform/staging/providers.tf
Attempting to resolve the error with the Drift check for terraform/cound.gov.
- #789 
- If it works for Staging, we need to do the same thing for demo & prod.
This is just ensuring that our infrastructure verification checks work properly and that our infrastructure is updated accordingly.
=> Api 729 recursive delete changes

poetry.lock, pyproject.toml
Fix for production release with Python 3.12
=> Making setuptools a regular dependency.

README.md
Explain what to expect when running `./run.sh` and `make run-profile` so that the user can determine if they have run correctly
=> Notes about running ./run.sh and make run-profile

app/organization/invite_rest.py, app/service_invite/rest.py, app/utils.py
Invites with login.gov work locally but not on staging, redis is suspected.
Don't expose PII on production.
=> debug staging

terraform/bootstrap/providers.tf, terraform/development/main.tf, terraform/development/providers.tf, terraform/sandbox/main.tf, terraform/sandbox/providers.tf, terraform/shared/egress_space/main.tf, terraform/shared/egress_space/providers.tf, terraform/shared/egress_space/variables.tf, terraform/shared/ses/main.tf, terraform/shared/ses/providers.tf, terraform/shared/ses/variables.tf, terraform/shared/sns/main.tf, terraform/shared/sns/providers.tf, terraform/shared/sns/variables.tf, terraform/staging/main.tf, terraform/staging/providers.tf
This changeset reverts the rest of our recent Terraform changes to make sure deployments are working properly.
Again, these will be re-introduced once we figure out the resource management piece.
- As with the previous change reverts for our Terraform scripts, this will re-introduce a deprecated attribute warning.
=> Revert the rest of our Terraform changes

app/config.py
Remove some settings for a template preview functionality that was never implemented.
N/A
=> remove template preview api stuff

Makefile, pyproject.toml
This changeset mirrors changes in our admin repo that make using poetry a little better and more consistent for dependency management.
- Helps us keep our dependencies up-to-date locally and in sync with what is merged remotely.
=> Mirror admin repo poetry updates

poetry.lock
This changeset updates notifications-utils to 0.4.5, which includes a few minor fixes and several dependency updates.
- Includes several dependency updates to help keep our project up-to-date and secure.
=> Update utils to 0.4.5

docs/all.md
Add a couple concrete examples of how to run commands with cloud foundry
N/A
=> add examples of common commands

.github/workflows/deploy.yml, app/config_files/templates.json
This should update the templates.json file if it changed when deploying.
#658
=> If the templates.json file changes, update it.

.github/workflows/deploy-demo.yml, .github/workflows/deploy-prod.yml
=> Adding template update steps for demo and prod.

.github/workflows/checks.yml, poetry.lock, pyproject.toml
This changeset updates the gunicorn dependency to the latest release to address a recent CVE.
- This also removes the ignored CVE from our dependency audit checks to make sure we're covered properly again.
=> Update gunicorn to latest release

app/notifications/rest.py, app/service/rest.py
A couple users reported discrepancies in their 7 day reports.  These users had limited folder permissions.  It is not clear if has anything to do with that or if it is user error.  Add some debugging to hopefully (?) clarify things.  Although, I am not seeing how folder permissions play in at all.
There might be some leak of PII when these debug statements run, so therefore they are kept at 'debug' level, whereas production normally runs at 'info' level.
=> add some debug around report generation

terraform/README.md
Add an error I experienced to the Troubleshooting section of the Terraform README
=> Add SSB error to README

runtime.txt
This changeset updates the runtime.txt file to match the recent Python version pinning that we had to do to fix a dependency issue.
- We are pinning to a stable and supported release of Python in cloud.gov / Cloud Foundry for now.
=> Fix runtime.txt for cloud.gov and Python

app/delivery/send_to_providers.py, app/user/rest.py, notifications_utils/clients/redis/redis_client.py, tests/app/service_invite/test_service_invite_rest.py, tests/app/user/test_rest_verify.py, tests/notifications_utils/clients/redis/test_redis_client.py
Fix lamentable oversight.  raw_set and raw_get no longer exist
N/A
=> fix raw_set and raw_get

deploy-config/production.yml
This changeset increases our memory for the API app and its corresponding workers to 2 GB each.
- Increasing the amount of memory available will help with application stability, though we should also look into what is starting to consume more memory in the app as well.
=> Increased production memory to 2 GB

.github/workflows/deploy-demo.yml, .github/workflows/deploy-prod.yml
Extend the upgrade in #1114 into demo and prod environment workflows
=> Upgrade tj-actions from v41 to v44 in Demo and Prod

.github/workflows/deploy-demo.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy.yml
Add `/**` to deploy paths per documentation:
https://github.com/tj-actions/changed-files?tab=readme-ov-file#examples-
Go to _Get all changed files using a list of files_
=> Update deploy paths

manifest.yml, terraform/demo/main.tf, terraform/production/main.tf, terraform/staging/main.tf
This is a production deploy for 6/27/2024.  [Full release notes are here!](https://github.com/GSA/notifications-api/releases/tag/06-27-2024)
- All changes have been reviewed and tested prior to being included here.
=> 06/27/2024 Production Deploy

docs/all.md
Add debug steps for missing message issue.
N/A
=> add debug steps

app/user/rest.py
See [compliance #46](https://github.com/GSA/us-notify-compliance/issues/46)
See [compliance #46](https://github.com/GSA/us-notify-compliance/issues/46)
=> add new api for compliance #46

docs/all.md, terraform/README.md
- Add recently-encountered errors to the Terraform Troubleshooting section
- Link to the Terraform README from the other docs
=> Troubleshooting additions

deploy-config/production.yml
This changeset updates the memory available to the API app and workers to be 4 GB to improve app stability and performance.
- None with this changeset.
=> Increased API and worker app memory to 4GB

docs/all.md
Instructions on missing Network Policy.
These are manual steps to replicate what's also done with this Terraform: https://github.com/GSA/notifications-admin/pull/1779
A part of issue https://github.com/GSA/notifications-api/issues/883
=>  Troubleshooting section: network policy

app/commands.py
Get sms senders for a given service.
N/A
=> new command to look at sms senders

terraform/README.md
A documentation PR
* Add a **maintenance checklist** of version numbers to keep an eye on
* Remove the **initial setup** section, no longer needed
* Link to our infra video
=> Jskinne3 maintenance checklist

app/config.py, app/dao/jobs_dao.py, tests/app/inbound_sms/test_rest.py, tests/app/service/test_rest.py
This PR is intended to set `page_size` from 50 to 20 in order to display a shorter page size for pagination on the Activity page
Ticket: https://github.com/GSA/notifications-api/issues/1280
=> update page_size to 20 from 50

.ds.baseline, .github/workflows/checks.yml, .github/workflows/deploy.yml
Rotate DANGEROUS_SALT when we deploy.
Note: the rotate action looks syntactically correct but I don't know how to test other than merging.
Security should be improved!
=> Use custom salt when using encryption library from notification_utils

.github/workflows/deploy.yml
First attempt got relatively close to working but we hit a 403.  According to doc, authorization should be "Bearer <token>" instead of "token <token>" so let's try that.
N/A
=> try Bearer instead of token

.github/workflows/deploy.yml
deploy script was read only.  Change that.
N/A
=> make it possible to write secrets

.github/workflows/deploy.yml
'secrets' is not a valid keyword.
N/A
=> remove secrets

app/user/rest.py
Add some debug messages to help track down problems with our efforts to run E2E tests against staging.
There is some sensitive info here so when we write debug messages, make sure they are not written on production.
=> debug messages for e2e test story

docs/adrs/0009-adr-implement-backstopjs-to-improve-qa.md, docs/adrs/README.md
This changeset updates ADR 0009 - BackstopJS integration - to be accepted now that it has undergone some review.
It also adds a few extra details about what the next steps will look like with firmer language that we will be integrating this as a new job in our CI/CD process.
* The inclusion of BackstopJS would be adding a new dependency to our project, so we need to make sure we pay attention to updates and such.
* When setting up new CI/CD jobs, we need to be mindful of the permissions we're allowing for the tools pulled into the container used in the runner as well as …
=> Change BackstopJS ADR (0009) to accepted and add more details

.ds.baseline, app/aws/s3.py, tests/app/aws/test_s3.py
Bring test coverage back to 95%
N/A
=> bring test coverage back to 95%

.github/workflows/deploy.yml
Fix syntax on `cf_command`.
Secrets are secure in command.
=> Fix syntax on cf command

.github/workflows/deploy.yml
This changeset attempts to fix another issue with the deploy command by setting and referring to an environment variable directly.
* We are being mindful of which env vars are secret vs. which are considered public with the code.
=> Refer to GitHub Action container environment variable

.github/workflows/deploy.yml
This changeset tries to wrap the Login.gov registration URL with quotes to get it to be properly handled in the shell environment.
* We are being mindful of which environment variables are secrets vs. those that are not.
=> Attempt quoting the Login.gov URL

.github/workflows/deploy.yml
This changeset tries to wrap the Login.gov registration URL with quotes to get it to be properly handled in the shell environment using the same pattern as the secret variables.
* We're being mindful of which values are secret vs. public.
=> Attempt quoting the Login.gov URL with var-name

.github/workflows/deploy-demo.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy.yml
Update demo and prod deploy scripts with newer maintained cg deploy tools.
=> Switch out deprecated deploy script tools in demo/prod yml files.

.github/workflows/deploy-demo.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy.yml
This changeset finalizes our updates for the cg-cli-tools across all environments and restores the check for updates to the egress proxy before deploying.
* We need to be mindful of how we're handling sensitive environment variables.
=> Finalize updates for cg-cli-tools

.github/workflows/deploy-demo.yml, .github/workflows/deploy-prod.yml
This changeset fixes the references to the egress proxy spaces in the demo and prod environments.
* We need to make sure the egress proxy is deployed and updated properly.
=> Fix egress proxy space references

.github/workflows/deploy-demo.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy.yml
This is a production deploy for 10/16/2024.  [Full release notes are here!](https://github.com/GSA/notifications-api/releases/tag/10-16-2024-2)
* All changes have been reviewed and tested prior to being included here.
=> 10-16-2024 Production Deploy #2

.github/workflows/deploy-demo.yml, .github/workflows/deploy-prod.yml
This is a quick hot fix to the `production` branch to fix an incorrect name reference for the production cloud.gov space.
* N/A for this change.
=> 10-16-2024 Production Hot Fix

.github/workflows/deploy-prod.yml, app/aws/s3.py
This changeset includes a hot fix to make sure older reports are able to be retrieved from the activity pages.
* N/A with this change.
=> 10-16-2024 Production Deploy Hot Fix #2

deploy-config/production.yml
This changeset increases the number of Celery workers available to our app in the production environment.  It also bumps the amount of memory available to them to 3G each.
* N/A - this will help improve application stability.
=> Increase Celery resources

app/clients/__init__.py, deploy-config/production.yml
This is a production hot fix in an attempt to fix the connection refused and broken pipe errors we're seeing, which we think are what are causing the other errors to take place.
* N/A with this release; focusing on increasing application stability.
=> 11/05/2024 Production Hot Fix Deploy

app/dao/services_dao.py, tests/app/service/test_rest.py
Removed `.scalars()` from the db execute command due to it returning only the first column of the result set and giving us back an incomplete data structure. Test coverage wasn't in place for this logic so it was missed before. Added test coverage.
It's worth noting that the dashboard graph wasn't displaying properly for me locally. Once `.scalars()` was removed, the graph displayed correctly.
None
=> No attribute day bug

docs/all.md
Added a broad description about feature flag strategy.
=> Added section about feature flagging

app/config.py
This is another Celery worker configuration adjustment to try and find the right balance between letting worker processes complete tasks vs. restarting them after some time to keep memory and other resources free.
* N/A with this change; we're working on improving site stability and performance.
=> 11/15/2024 Celery Worker config adjustment

terraform/demo/main.tf, terraform/production/main.tf
Increase demo db to small and production db to medium
N/A
=> upgrade demo and production dbs

app/celery/tasks.py
Try to reduce unnecessary retries on IntegrityError exceptions pending a rewrite of this area.
N/A
=> change retries

app/clients/cloudwatch/aws_cloudwatch.py
AWS fills out the 'phoneCarrier' field in the delivery receipt on a best effort basis.  If it doesn't know the carrier, it omits the 'phoneCarrier' key as well as the value, so the structure of the JSON is not reliable.  Make parsing more flexible so it is not counting on that field to exist.
N/A
=> fix json structure bug in mass updates

tests/app/clients/test_aws_cloudwatch.py
Add tests for test coverage
N/A
=> more tests

.github/actions/setup-project/action.yml, Makefile, app/aws/s3.py, poetry.lock, pyproject.toml
A user did something unexpected.  They managed to create a file that contained a BOM, but which bypassed our BOM handling.  Evidently it was not robust enough.
I have added .lstrip(\ufeff) and removed the code that wasn't catching everything.  I'm also going to write a tick to add .lstrip() before we upload the file on the admin side.
N/A
=> fix BOM issue again

.github/workflows/adr-accepted.yml, .github/workflows/daily_checks.yml, .github/workflows/deploy-demo.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy.yml, .github/workflows/terraform-demo.yml, .github/workflows/terraform-production.yml, .github/workflows/terraform-staging.yml
This changeset updates many of our GitHub Action references to point to the latest versions to ensure they are kept up-to-date.  This helps address any improvements and security patches that have been made to them.
* Keeps our reliance on third-party tools up-to-date to account for improvements and security patches to address any vulnerabilities.
=> Update GitHub Action References

.ds.baseline, Makefile, app/dao/services_dao.py, tests/app/aws/test_s3.py, tests/app/dao/notification_dao/test_notification_dao.py, tests/app/dao/test_services_get_specific_hours.py, tests/app/test_commands.py
I used the report to show me the files that had the biggest disparity between un tested code and wrote a few tests to cover the lines in the least amount of tests possible.
=> Added tests to increase code coverage

app/delivery/send_to_providers.py
Prove once and for all that the code is using the right sender number, and the problem is somewhere in pinpoint config.
N/A
=> add even more debug for sender number

.github/workflows/dependabot-auto-merge.yml
The previous attempt at the auto-merge script had an indent problem.  Clean up commented out script as well.
N/A
=> fix indent problem

.github/workflows/dependabot-auto-merge.yml
Github requires a special approver action for auto-approved PRs.
N/A
=> use hmarr autoapprove action

app/celery/scheduled_tasks.py, app/delivery/send_to_providers.py, app/notifications/process_notifications.py, app/user/rest.py
At some point the ability for the user to change their phone number in the User profile broke and this was not noticed for some period of time.  Restore this functionality.
N/A
=> fix phone number changing

migrations/versions/0416_readd_e2e_test_user.py
=> update e2e test user

.github/workflows/deploy-demo.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy.yml
Temporarily comment out update-templates
N/A
=> comment out update templates

.github/workflows/checks.yml, .github/workflows/deploy-demo.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy.yml
Try to get update-templates working again
N/A
=> fix update-templates

.github/workflows/restage-apps.yml
Specify the manifest file, which has of course been renamed to something else.
N/A
=> do a manifest.yml push to load new env variables

.github/workflows/restage-apps.yml
Try to pinpoint why the manifest file cannot be found by the restage_apps script
N/A
=> ugh revert and fix

.github/workflows/restage-apps.yml
Try to debug why manifest file cannot be found.
N/A
=> Restage app work

app/delivery/send_to_providers.py
Debugging on staging indicated the problem is actually a regression in the email template to send invites.   Since this is almost the only use case we have for an email template, fix it after the fact for now.
N/A
=> fix invites again

docs/all.md
Instructions for rotating the login.gov certificate
This is a manual process and it is necessary for the person doing the rotation to take adequate precautions (i.e. delete their local copy of the certificate after performing all the steps and so on).
=> refreshing login.gov cert instructions

README.md, docs/all.md
This changeset updates our runbook for the DNS and domain management:
* Add instructions and steps for how to perform the necessary actions to add and/or remove domains
* Update links to existing resources
* Add links to additional documentation
* All documentation and referenced resources are public and open source.
=> Update instructions for managing DNS and domain configuration

.profile, app/aws/s3.py
This changeset updates the no_proxy environment variable to allow S3 through.  It also updates our error handling connecting to S3.
* We need the egress proxy to function properly, and traffic to S3 should be allowed.
=> Update no_proxy and S3 error handling

.github/dependabot.yml, docs/openapi.yml
Added me to automatically be review for dependency updates.
=> Update dependabot assignee

app/socket_handlers.py
Added @socketio.on("connect") and @socketio.on("disconnect") handlers to log and manage Socket.IO connections. The intention is to resolve connection issues by ensuring the server properly acknowledges incoming WebSocket clients.
=> Added @socketio.on(connect) and @socketio.on(disconnect) 

app/job/rest.py, tests/app/job/test_rest.py
Let's reject calls that are malformed or apparently malicious with a 403 code.
Minor enhancement
=> fix input handling

app/job/rest.py, app/notifications/rest.py, app/organization/invite_rest.py, app/organization/rest.py, app/provider_details/rest.py, app/service/rest.py, app/service_invite/rest.py, app/template/rest.py, app/template_folder/rest.py, app/template_statistics/rest.py, app/upload/rest.py, app/user/rest.py, app/utils.py, app/webauthn/rest.py, tests/app/job/test_rest.py, tests/app/test_utils.py
Extend our input checking scheme from the jobs module to all modules.
Adds defense in depth.
=> more input checking

app/user/rest.py, notifications_utils/logging.py
Add some more debugging to try to understand what is happening with invitations.
N/A
=> more invite debug

application.py, gunicorn_entry.py, scripts/migrate_and_run_web.sh
We need to force gevent monkey patching to happen first, before anything else.
N/A
=> try to force monkey patching to happen first

notifications_python_client/base.py, tests/notifications-python-client/test_base.py
This changeset modifies the notifications_python_client we pulled in to no longer reference the UK Notify system.
* Removes references of the UK Notify URLs and replaces them with our own.
=> Modify notifications_python_client

app/notifications/rest.py
Add gevent.sleep(0) as a keep-alive during long report generation so the report can complete.
N/A
=> add gevent.sleep(0) as a keep alive

notifications_utils/s3.py
Fix the names of the access key id and secret access key
N/A
=> fix secret names

notifications_utils/s3.py
Keep trying to find the credentials
N/A
=> Report performance

app/config.py
Fix the schedule for report generation
N/A
=> fix schedule

app/aws/s3.py, app/celery/tasks.py
Reformat report columns to change raw data into what is expected in the presentation.
Note: moving to backend generation like this, there is an issue with time.  The backend report has time in UTC, whereas the current report shows in the user's preferred timezone.
N/A
=> cleanup backend report generation

app/dao/jobs_dao.py, app/job/rest.py, app/service/rest.py, app/template_statistics/rest.py, tests/app/template_folder/test_template_folder_rest.py, tests/app/template_statistics/test_rest.py, tests/app/test_security_headers.py
Backend support for FE change. 
https://github.com/GSA/notifications-admin/pull/2862
=> Added changes to support extra day in activity chart

app/organization/invite_rest.py, tests/app/organization/test_invite_rest.py
Getting organization invites working again.  See matching PR on the admin side.
N/A
=> fix org invites

deploy-config/staging.yml
This changeset increases the worker process memory slightly in staging to help with running out of memory issues we are starting to see with our testing.
* None; this is in our staging environment and we need to adjust given recent application and infrastructure updates.
=> Update staging worker process memory

app/job/rest.py, tests/app/job/test_rest.py
Added new endpoint that the admin UI can poll against for status updates that is lightweight
=> Created new endpoint for polling
