GSA/notifications-api

manifest.yml
We should keep an eye on the cloud.gov supplied python_buildpack and revert to it once it is at `>= 1.7.58`
Bug report that led to solution: https://github.com/cloudfoundry/python-buildpack/issues/574
https://github.com/cloudfoundry/python-buildpack/releases/tag/v1.7.58
=> Specify 1.7.58 buildpack with fix for missing Python.h

devcontainer-api/.devcontainer.json
**NOTE:** Requires running `Remote-Containers: Rebuild container` in vscode command pallette to take effect (alternatively, you can destroy the salient docker containers)
These changes should eliminate most pylint missing import false positives.
=> Fix pylint import errors

manifest.yml
Last bit of glue between passing the keys from github actions secrets into the deployed app.
=> Pass AWS creds to application environment

.github/workflows/checks.yml, app/aws/s3.py, app/cloudfoundry_config.py, app/config.py, tests/app/aws/test_s3.py, tests/app/celery/test_ftp_update_tasks.py, tests/app/test_cloudfoundry_config.py
cloud.gov-supplied s3 buckets are in a different region than current SES/SNS/SQS services, so we need to specify the region alongside the bucket-specific access credentials.
https://github.com/GSA/notifications-admin/issues/89
=> Proactively specify aws region for s3 operations

.github/workflows/checks.yml, .github/workflows/daily_checks.yml, Makefile
`make audit` will still run against test dependencies, but CI/CD should only care about things that are installed on the server.
=> Only run pip-audit on runtime dependencies in CI

.github/workflows/deploy.yml
This uses the existing project setup action in the deploy workflow, replacing redundant commands.
This popped up because we're now relying on `pipenv` to install dependencies, and need to pull that in.
=> Use setup action in deploy workflow

app/config.py, tests/app/test_cloudfoundry_config.py
Forgotten update from the cloud.gov migration.
#109
=> Replace old notifications-api service prefix with notify-api

.github/actions/deploy-proxy/action.yml, .github/workflows/deploy-demo.yml, .github/workflows/deploy.yml
Short-term effect is deploying the updates that close #117
Long-term we can be more specific with the version that we want to deploy, which will make it easier to test changes in staging without effecting demo/prod.
=> Enable deploying exact version of cg-egress-proxy

deploy-config/demo.yml, deploy-config/production.yml, deploy-config/staging.yml, manifest.yml
Scheduled messages weren't being sent because celery beat wasn't running.
https://github.com/GSA/notifications-admin/issues/98
=> Run celery beat on cloud.gov

.github/actions/deploy-proxy/action.yml, Procfile.dev
Relevant PRs have been merged, so move our cg-egress-proxy deploy from my branch to the main repo.
closes #113 
Also sneaks a change it to include celery-beat in the list of processes to start up in development.
=> Official egress proxy

.github/workflows/checks.yml, .github/workflows/daily_checks.yml, app/__init__.py, app/authentication/auth.py, app/commands.py, app/config.py, app/docs/__init__.py, docs/api-usage.md, docs/openapi.yml, docs/testing.md, docs/writing-public-apis.md
This should be expanded as we work further on the API, but it's a good baseline, and allows OWASP Zap to discover more than just the `_status` route.
closes #27
=> Add OpenAPI spec for selected api endpoints

deploy-config/demo.yml, deploy-config/sandbox.yml, deploy-config/staging.yml, scripts/migrate_and_run_web.sh
Changes:
* allows for app to receive process signals from cloud foundry. [Doc source](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#start-commands:~:text=If%20you%20override,your%20own%20process.)
* Uses 2 web instances in every environment. The combination of 1 instance with `--strategy rolling` and `--no-wait` appears to be the cause of #128
closes #128
=> Exec web startup command

docs/api-usage.md, docs/openapi.yml
* Add a link to the postman document 10x put together, which I think is a good summation of everything we know about the API.
* Clarify, a bit, how to use the openapi spec
* Add `/v2/templates` and `/v2/template/{uuid}` routes to openapi spec. This and the existing post SMS route are the basis of sending an SMS via API.
closes #53
=> Update API documentation

Pipfile, Pipfile.lock
Addresses pip-audit finding.
Freezes `packaging` because pipenv wasn't respecting the version requirement that `pip-audit` gave for that package.
Also updated other packages that still fit within Pipfile version requirements.
closes #138
=> Dependency updates

app/models.py, tests/app/test_model.py
Returning an empty-dictionary here causes the UI to act as if though personalization was redacted, which is a fine safe behavior.
Closes #148
=> Gracefully handle decryption errors in past-7-days notification reports

.github/workflows/checks.yml, .github/workflows/daily_checks.yml, Makefile, docker-compose.devcontainer.yml
Just need to update to most recent action to prevent a false finding.
Also removes the restart: always to prevent an unattached devcontainer from being spun up when Docker is launched
closes #159
=> Pip audit mitigation

docs/system-description.md
This is going to be referenced in the FIPS 199 doc, SSPP, and probably others. The description goes after what I want to have authorized, which is a slightly larger scope than our initial pilot plans (includes emails and API access, for instance)
Work towards https://github.com/GSA/notifications-admin/issues/307
The section instructions state:
> Instruction: Insert a brief high-level description of the system, the system environment and the purpose of the system. The description should be consistent with the description found in the System Security Plan (SSP).
=> Add a system description entry to docs

terraform/create_service_account.sh
Slight tweak for the cf-cli output format.
I had to update to 8 for the ssb work, so keeping it all in sync. Day-to-day 7 should still work fine if you're not using this script.
=> Tweak tail & jq usage to parse cf-cli@8 output

terraform/demo/main.tf, terraform/production/main.tf, terraform/sandbox/main.tf, terraform/shared/sns/main.tf, terraform/shared/sns/providers.tf, terraform/shared/sns/variables.tf, terraform/staging/main.tf
Adds commented-out versions for demo and prod that will be uncommented as various support requests are processed. Those tasks are tracked in TODO list in #38 
For spend limit: $1000 in production matches the cost estimate for the base year, demo & staging/sandbox/dev are each set to 25, but in practice we haven't gone above $2 so I'm amenable to lowering those if you think it's wise. The one reason not to is that updating that value in-place seems to not currently work, so changing it involves destroying the instance and re-creating it. It's a bit of a pain, so I set the values higher than currently needed now, but it also doesn't affect the things with long lead times like phone number provisioning so it's not a blocker.
=> Provision sns via terraform in staging

.github/actions/deploy-proxy/action.yml, Pipfile.lock
* Update notifications-utils to get most recent version of encryption facade.
* Switch egress proxy back to main repo
=> Utils lib and proxy deploy update

app/dao/users_dao.py, tests/app/dao/test_users_dao.py
* use `secrets` module instead of `random` for generating random number
* removes code to avoid repeating digits, since that just removes entropy
* increases token length to 6 digits. This will need to be merged alongside a matching admin PR to avoid breaking login form.
closes #181
=> Use cryptographically secure random number for sms codes

app/dao/users_dao.py, terraform/demo/main.tf, terraform/sandbox/main.tf, tests/app/dao/test_users_dao.py
* Looks like we can't use us-gov-east-1 for SMS sending, so switching the entire demo setup over to the commercial AWS account.
* Also lays groundwork for sandbox to use its own SMS service, since sharing isn't supported in space-scoped brokers.
Work in support of #180 and #38
=> Brokerpak setup updates

terraform/production/main.tf, terraform/shared/ses/main.tf, terraform/shared/ses/variables.tf, terraform/staging/main.tf
Adds a custom mail-from to allow mail to appear to be delivered from `mail.<insert domain that we actually get>.gov` rather than `amazonses.com`
There's a chance the apply to staging won't work if the broker doesn't accept this change. If that happens, it is not a problem to manually delete the staging ses service instance using `terraform destroy -target=module.ses_email` and re-run the deploy action. That won't be a problem for prod because nothing has been setup yet.
Closes https://github.com/GSA/notifications-admin/issues/397
=> Add a mail-from subdomain to staging and prod ses

Pipfile.lock, app/config.py, app/notifications/process_notifications.py, app/notifications/validators.py, app/v2/errors.py, tests/app/notifications/test_process_notification.py, tests/app/notifications/test_validators.py
This uses a validation check to enforce a daily limit for messages. We're just reusing the service-specific daily limit, so this adds a Redis key for a cross-service total and then increments it for any message sent.
The keys are stored in `notification-utils`, which allows it to be used in the UI, so the next steps are:
=> Add a total-message daily limit

.github/workflows/checks.yml, .github/workflows/daily_checks.yml, README.md, app/cloudfoundry_config.py, app/config.py, docs/infra-overview.md, sample.env, terraform/create_service_account.sh, terraform/development/main.tf, terraform/development/providers.tf, terraform/development/run.sh, terraform/development/variables.tf, tests/app/aws/test_s3.py, tests/app/clients/test_aws_sns.py, tests/app/delivery/test_send_to_providers.py
#194 
* adds `terraform/development` with a one-stop shop `run.sh` script for creating s3 buckets and service keys for SES and SNS
* removes all uses of generic `AWS_*` environment variables
Gotchas:
* for current developers (so, just you, @stvnrlly) you'll need to either blow away your development database or run `pipenv run flask db downgrade 0390` before updating your `.env` file. Then update the .env and run `make bootstrap` and everything will be good.
* There ~will be~ is a [corresponding admin PR](https://github.com/GSA/notifications-admin/pull/420). They can be merged independently, but while there is a mismatch sending SMS via CSV upload will be broken, because the two sides will be talking to different s3 buckets.
=> Add scripts for provisioning development credentials

.github/workflows/drift.yml, docs/testing.md
This workflow will run each morning to ensure that terraform knows about all infrastructure changes.
In support of control CM-6.1
Production check should be uncommented once it exists.
=> Add infrastructure drift detector

.github/workflows/restage-apps.yml, terraform/production/main.tf
Changes
* add a manually-run workflow to restage apps in `notify-<env>` and `notify-<env>-egress`
* Switch `notify-prod` space to `notify-production` so that the space and environment names are consistent
There will be a matching PR on usnotify-ssb to restage the ssb apps and update the space name, and one on admin for the space name. Documentation for using this workflow has already been added as a task on #192 
Work towards #203
=> Add workflow to restage apps

deploy-config/egress_proxy/notify-api-demo.allow.acl
Forgot to update the region in the proxy config when we moved out of tts-sandbox.
Demo sends email via us-west-2 because we can have multiple environments there, but SNS uses per-region settings so all of our environments have their own region.
Regions in the `notify-api-<env>.allow.acl` URLs should match what is specified in `terraform/<env>/main.tf`
=> Allow demo to send SMS via us-east-1 region through proxy

.github/workflows/deploy-demo.yml, .github/workflows/deploy.yml
closes #208 
This will need to be deployed to demo today to prevent the drift detector action from continuing to fail.
=> Run terraform on deploy when shared modules change

docs/deploying.md, terraform/bootstrap/main.tf, terraform/bootstrap/providers.tf, terraform/development/main.tf, terraform/development/variables.tf
I have a ticket to service desk asking for an authoritative answer to what the VPN & Zscaler egress IPs are. Once we have that answer we can lock down the development service keys more appropriately. This change keeps the prior behavior that existed before the SSB updates.
=> Keep development SES & SNS keys open

.github/workflows/checks.yml, .gitignore, Makefile
Initial steps to creating coverage in API repo.
Using `coverage.py` as the coverage tool. Widely used and easy to implement. Commands have been added to the Makefile. When running `make test` the output should appear as below. The coverage threshold has been set to 50% for now to avoid every PR from failing. As we fix tests/work on the code we can raise the threshold up to 90% where we eventually want to be. The threshold is the same for Github Actions.
When running the coverage report, open the `.coverage_cache` and select `index.html` then open with browser.
=> Add coverage report to API

app/__init__.py, docs/testing.md
* CORS headers removed because browsers should not interact with API directly
* Updated error handling to return expected content-type for JSON error messages
closes #234
=> Address moderate and low owasp findings

.github/actions/deploy-proxy/action.yml
Proxy binary is included in the repo since https://github.com/GSA-TTS/cg-egress-proxy/pull/20 and https://github.com/GSA-TTS/cg-egress-proxy/pull/23
=> Deploy bundled proxy instead of building it each time (API)

.github/actions/deploy-proxy/action.yml, docs/run-book.md
closes #247 
also moves cg-egress-proxy back to main branch since the `stack: cflinuxfs4` change there was merged.
=> Run book updates

docs/infra-overview.md
You have to have at least the `acme-challenge` record created before you can create the domain service. There is also a link to the exact records needed already within the admin terraform where that module would be commented out.
=> Update step order for clean-env deploys

app/schemas.py, migrations/versions/0395_remove_intl_letters_perm.py
The only error I was seeing was that "international_letters" appeared in the total set of permissions, but did not appear in models.SERVICE_PERMISSION_TYPES.  Hence, it was being rejected as an invalid permission.  I excluded it and now I can toggle Live to On/Off locally.
=> notify-301 allow services to move to production

.github/ISSUE_TEMPLATE/create-a-new-adr.md, .github/ISSUE_TEMPLATE/create-new-adr-form.yml
Addresses issue #288
This changeset adds a custom issue template for use within GitHub itself to help draft new Architectural Decision Records (ADRs).
Note that we'll still ultimately have to create the actual ADR as a Markdown file that lives in the `doc/adrs/` folder.
- This issue template is a verbatim copy of what is in the repo already, just setup for use with GitHub itself.
- The template has a section in it to call out Security Considerations within the ADR itself.
=> Create custom ADR GitHub template(s)

docs/run-book.md
This add the process for downloading our compliance-related test results and uploading them to the place where we store them.
=> Add steps for exporting test results

docs/adrs/README.md
This changeset fixes the formatting of the Architecture Decision Log table; it was missing a cell in the header row.
- None
=> Fix the Architecture Decision Log display

app/celery/provider_tasks.py, app/clients/cloudwatch/aws_cloudwatch.py, app/dao/notifications_dao.py, app/notifications/process_notifications.py, tests/app/dao/notification_dao/test_notification_dao.py
When a notification is declared successful, the original code did:
1. mark the notification as 'delivered'
2. remove the phone number from the to and normalised_to fields
in two separate queries.
While this worked fine locally, on staging it appears like step #2 is failing, leading to the result that users can see successful notifications in their reports with PII, which is not desirable.
Change the code so that the same query that marks the notification as 'delivered' also removes the phone numbers, and add a unit test to show it works.   This currently cannot be reproduced locally, so will need to be tested on staging.
=> notify-api-317 fix the scrubbing of pii for successful notifications

app/dao/notifications_dao.py
The method sanitize_succcessful_notification_by_id has been failing on staging, even though it works locally.  The error relates to connecting to the db and the suspicion is the problem has something to do with esoteric aspects of the SQLAlchemy query language.   Try to work around this by writing the query in ordinary sql.
=> try using vanilla sql for problematic query

app/config.py
Previously nightly and reporting tasks were scheduled on New York time.  Adjust them to UTC time.
=> Examine and re-align jobs that run based on UTC time

deploy-config/egress_proxy/notify-api-staging.allow.acl
Helps address an issue with #317 
This changeset adds another endpoint to the staging egress proxy to enable access to AWS CloudWatch logs.
NOTE:  We will have to probably do this for production as well.
- This opens another specific endpoint for an AWS service with our egress proxy.  We need to do this in order to retrieve information that is necessary for the application to function properly.
=> Add logs AWS endpoint to staging proxy allow list

Makefile
Failing if code coverage was below a threshold was already part of the GitHub checks, but the fail threshold was set to 50%.  Increase the threshold to the current level of code coverage (88%).
=> notify-admin-638 fail if code coverage below current level of 88%

.github/workflows/checks.yml, Makefile, Pipfile, app/__init__.py, app/commands.py
The vulture tool currently only finds a handful of 'unused' variables.  Removing them is problematical, so I used # noqa because otherwise vulture will fail the build.
=> notify-api-387 Scan projects for unused code

app/aws/s3.py, app/clients/__init__.py, app/clients/cloudwatch/aws_cloudwatch.py, app/clients/email/aws_ses.py, app/clients/sms/aws_sns.py, deploy-config/egress_proxy/notify-api-demo.allow.acl, deploy-config/egress_proxy/notify-api-production.allow.acl, deploy-config/egress_proxy/notify-api-staging.allow.acl
Addresses #274
This changeset switches AWS service touchpoints to use their FIPS-enabled counterparts.  Note that S3 has some specific configuration associated with it.
This changeset also updates our allow ACLs to cover the FIPS-enabled endpoints.  We should investigate removing the non-FIPS endpoints as a part of this.
- Helps ensure security compliance of our system by switching to the FIPS-enabled AWS endpoints.
=> Switch to using FIPS-enabled endpoints

.github/workflows/deploy-demo.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy.yml, .github/workflows/restage-apps.yml, terraform/bootstrap/main.tf, terraform/create_service_account.sh, terraform/demo/main.tf, terraform/destroy_service_account.sh, terraform/development/main.tf, terraform/development/reset.sh, terraform/development/run.sh, terraform/ops/cloudgov_user_report.py, terraform/production/main.tf, terraform/sandbox/main.tf, terraform/set_space_egress.sh, terraform/staging/main.tf
Part of #439
This changeset adjusts our references to the cloud.gov org we are using from gsa-tts-benefits-studio-prototyping to gsa-tts-benefits-studio.
- None for this change.
=> Update cloud.gov org references

Pipfile
It was pinned because of this issue which has only recently been fixed (July):
fix thread worker: fix socket removal from the queue at checkout 21.x
I upgrade to the latest 21.2.0 and am seeing no problems.
=> notify-api-389 unpin gunicorn

app/service/rest.py
This fixes an error where the API expected a `total_message_limit`, but the UI was not sending one. We are hard-coding it, as it is not user-settable, but this is likely to change in the future as we revise limit handling.
=> Insert total_message_limit into service creation

Makefile, app/commands.py
When updating default templates, we may be adding a new one (or one may have been dropped somehow). This adds a conditional to the command to add that template instead of failing.
=> Add default template when it does not exist

.github/workflows/checks.yml, migrations/versions/0401_add_e2e_test_user.py, tests/app/aws/test_s3.py, tests/app/notifications/test_validators.py
This is the migration script to set up the e2e test user.  It works fine locally, but remotely the build is failing because password is None.  The password is set here:
password = os.getenv("NOTIFY_E2E_TEST_PASSWORD")
So I'm thinking the environment variable may not be set wherever this builds.  However, I don't have permission to view secrets in GitHub, so can't check.
=> add migration for e2e tests and improve code coverage

deploy-config/production.yml
Fixes #471 
This changes what the API considers the "proper" place to send users to the UI. It's used in populating email templates for invites.
=> Switch ADMIN_BASE_URL to fancier URL

migrations/versions/0402_total_message_limit_default.py
Addresses #474
This changeset adds a migration to add a default total message limit to any pre-existing service that does not already have one set.  It bases this value on the default set in the Flask app config.
- None with this change.
=> Add total message limit default to existing services

.github/workflows/deploy-demo.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy.yml, manifest.yml
This changeset actually adds the missing E2E test environment variables to the cf push command.
- Continue making sure we don't expose secrets.
=> Add missing environment variables from cf push

.github/workflows/adr-accepted.yml
The primary purpose of this is to try to trigger status checks, which aren't running on their own. The reason is that GitHub doesn't allow workflow-based pushes to trigger other workflows in order to prevent possible infinite loops.
Supposedly, using an SSH deploy key to check out the codebase will allow status checks.
=> Switch ADR action to our own repo

.github/workflows/checks.yml
This PR fixes the dynamic-scan job, which is now failing in our PR checks due to missing environment variables.
It appears there was a change in how the `zaproxy` Docker image was being referenced and prior to this PR, the `weekly` image was being used despite us having it configured to pull down the `stable` package.
As of the morning of this PR being created, only the `stable` package started to be pulled down, which wouldn't run correctly.  We had to explicit set the action to pull the `weekly` Docker image to get a working build again.
- Be mindful of secrets being referenced in code.
=> Fix the dynamic-scan job

app/clients/cloudwatch/aws_cloudwatch.py, tests/app/clients/test_aws_cloudwatch.py
The previous solution for "messages hang in pending forever" was attempting to do some string manipulation of an environment variable to determine what the aws account number was.  Unfortunately the demo environment used multiple regions and the sns region was different from the ses region, causing corruption of the cloudwatch log group name we were trying to construct and making it impossible to retrieve delivery receipts.
The new implementation relies on counting colons in the arn string.  The account number ice always at index 4 if you split the string by colons, whether you are in gov cloud or regular aws.
=> notify-api-360 stop worrying about aws regions

.github/workflows/checks.yml, .github/workflows/daily_checks.yml
The OWASP ZAP scan GitHub Actions have been updated recently and we need to make sure our GitHub Actions account for the recent changes.  This changeset makes sure we are using the latest version of the OWASP ZAP API scan, the correct Docker image, and adjusts the name of the step to accurately reflect what scan is being run.
- Helps ensure that we are properly scanning our pull requests and repo.
=> Update OWASP ZAP scans

app/dao/services_dao.py, app/service/rest.py, tests/app/conftest.py, tests/app/db.py, tests/app/service/test_rest.py
We decided it was best to remove the default sender from the `api` (when a service is created a default sms sender is created with it) rather than relying on removing the ability for the user to see it on the front end. This route removes the `default sms sender` from showing up when in the service settings or during the message flow on the front end.
~A migration would be the next step to remove the default sender from already existing services.~  A new issue has been created to account for the next step, which will be to create a command to run a one-off task to clean up existing services (#540).
Changes:
- Added flag to the `dao_create_service()` function to only `insert a default sms sender` when in the `test` environment.
- Fixed tests that needed the updated flag.
=> Added flag to remove default sender from user list

Makefile, README.md, poetry.lock, pyproject.toml
This changeset updates a few more dependencies and addresses the challenges we have had in keeping the `notifications-utils` dependency up-to-date.  The changes include instructions on what to do going forward for future `notifications-utils` updates.
- Helps keep our dependencies up-to-date.
=> Update more dependencies and fix notifications-utils

docs/adrs/0003-implementing-invite-expirations.md
This changeset updates ADR-0003 to clarify the work a bit more and remove a couple of extraneous steps.  The previous draft included provisions for creating a whole separate `expired` field, which is unnecessary.
h/t to @xlorepdarkhelm and @stvnrlly for catching this and asking about it!
- None with these changes; documentation update.
=> Update ADR-0003: InvitedUser Expirations

app/aws/s3.py, app/commands.py
Developers over time will accumulate csv files in their development csv buckets that don't get processed for whatever reason.  When this happens, it will be impossible for them to reset their admin environment via the reset.sh command, because it will fail on trying to delete the non-empty csv bucket.
Write a command that will purge the developer's csv bucket to assist with environment recovery.
=> write a csv bucket purge command

poetry.lock, pyproject.toml
This changeset updates the `notification-utils` dependency to 0.2.3 to address an issue we found with link formatting in our last production release.
- Helps keep our application running well with updated dependencies and addresses production issues.
=> Update notifications-utils to 0.2.3

migrations/versions/0408_fix_timezone_again.py
We need to check for nulls in the preferred_timezone_column as well.
=> notify-admin-931 fix timezone again via migration

docs/all.md
This changeset adds a bit more information to the one-off task details and helps clarify what to include in the command to pass to Cloud Foundry.
- None with this change; it's public documentation.
=> Expand one-off task details

app/config_files/templates.json
I found a bug. 
Use `[Join Service](((url)))` with the extra parentheses, otherwise the url link does not work.
=> Join Service: Bug fix - added extra parentheses

poetry.lock
This changeset updates the utils library to our 0.2.4 release.
- Keeps our own dependencies up to date.
=> Update utils to 0.2.4 release

app/clients/cloudwatch/aws_cloudwatch.py, migrations/versions/0409_fix_service_name.py
There was an error deep in the code where "phoneCarrier" was not found in a particular structure, for opt-outs. The fix was to make it default to "Unknown Carrier" if this situation happens when making the error response, fixing the bug and making it now track opt outs correctly.
Issue: #683
=> Api 683 make UI and reports reflect opt out numbers

app/clients/__init__.py, app/clients/email/__init__.py, app/clients/performance_platform/performance_platform_client.py, app/clients/sms/__init__.py, app/clients/sms/aws_sns.py, migrations/versions/0409_fix_service_name.py, tests/app/clients/test_sms.py
I did a little refactoring/adjusting to the method the clients are implemented, to use some more future-proof Python features:
1. The "interface" classes that existed are now all Protocols. This will allow for eventual inclusion of modern Python techniques like type hinting, allowing for both static and runtime checking of attributes.
2. All of the methods with a `raise NotImplementedError` have been decorated with `@abstractmethod` or `@abstractproperty` as applies. This will ensure that any class derived from these must implement those methods in order to run.
3. The `init_app()` method was existing in all of the concrete implementations of a client. As such, I factored it into being part of the base `Client` Protocol. There are other methods that I believe could also be moved to here …
=> Clean up client classes

poetry.lock
This changeset updates the notification-utils library to 0.2.5.
- Helps keep our project and its dependencies up-to-date.
=> Update utils to 0.2.5

poetry.lock
This changeset updates the jinja2 library to address a pip-audit finding.
- Keeps our dependencies up-to-date to resolve security findings and vulnerabilities.
=> Update jinja2 to latest release

.github/workflows/deploy.yml, deploy-config/demo.yml, deploy-config/production.yml, deploy-config/sandbox.yml, deploy-config/staging.yml
This changeset adjusts the REDIS_ENABLED environment variable to match how the admin app is set up to make sure the API properly connects to the Redis service.
The previous change didn't surface the environment variable fully, unfortunately.
- The API isn't currently talking to the Redis service in the cloud.gov environment.
=> Mirror Admin REDIS_ENABLED config

poetry.lock
This changeset updates notification-utils to 0.2.6 for dependency updates.
- Helps keep our application dependencies up-to-date to address security alerts.
=> Update notification-utils to 0.2.6

app/celery/scheduled_tasks.py, tests/app/celery/test_scheduled_tasks.py
1.  We origin added an alert that would send an email when the number of failed notifications being kept in the notification table went above a certain level:  2500, 5000, 7500, 9000, etc.
2. This alert was going to use redis to keep track of the last value for the level of failures, and was assumed to be working
3. But actually redis was not working at all on staging
4. Now that redis is working, there is an error because "last_value" comes back from redis_store.get() by default as bytes and we were not decoding it down to a string.
So this PR fixes the new error that appears in the logs, but is not terribly important. Once we remove the phone numbers from the database, this alert will go away as well.
=> fix redis issue causing error in log

app/dao/notifications_dao.py, app/job/rest.py, app/service/rest.py, app/user/rest.py, tests/app/celery/test_tasks.py, tests/app/dao/notification_dao/test_notification_dao.py, tests/app/dao/test_services_dao.py, tests/app/delivery/test_send_to_providers.py, tests/app/job/test_rest.py, tests/app/notifications/test_process_notification.py, tests/app/notifications/test_rest.py, tests/app/organization/test_rest.py, tests/app/public_contracts/test_GET_notification.py, tests/app/service/send_notification/test_send_notification.py, tests/app/service/test_rest.py, tests/app/service/test_sender.py, tests/app/user/test_rest_verify.py, tests/app/v2/notifications/test_get_notifications.py, tests/app/v2/notifications/test_post_notifications.py
Instead of writing phone numbers and email addresses to "to" and normalised_to columns In notifications table, write "1" to signify a record has been processed, but otherwise leave the columns (and the to and normalised_to fields in the Notifications model) untouched for now.
=> Notify api 742 don't write phone numbers or email addresses to db

app/aws/s3.py, tests/app/aws/test_s3.py
When we looked up the phone number from the job in s3, we were specifically looking for "phone number", but it might be "Phone number" or "pHoNe NuMbEr", so make it case insensitive and add a test.
This should fix the "click on any service that has weird-case jobs and everything fails" bug.
=> fix case sensitivity looking up phone number

app/delivery/send_to_providers.py
This changeset updates a try/except block to catch `Exception` instead of `BaseException`.  Using BaseException is an anti-pattern and [is not intended for user-defined code](https://docs.python.org/3.9/library/exceptions.html#BaseException); it can also lead to other unintended side effects if not handled properly.
This is enough of a concern that the new release of `flake8-bugbear` now issues warnings when it sees `BaseException` being caught without an immediate re-raise (see issue https://github.com/PyCQA/flake8-bugbear/issues/174 for more details).
=> Update try/except block to catch Exception

.profile, deploy-config/egress_proxy/notify-api-demo.allow.acl, deploy-config/egress_proxy/notify-api-production.allow.acl, deploy-config/egress_proxy/notify-api-staging.allow.acl
This changeset adds a missing egress proxy configuration environment variable.
This change is based on the [cg-egress-proxy deployment instructions](https://github.com/gsa-tts/cg-egress-proxy?tab=readme-ov-file#deploying-the-proxy-by-hand).
It also adds the Login.gov URLs to our egress allow ACLs.
- This will ensure that our application is correctly interacting with the egress proxy we have configured to restrict traffic.
=> Adding missing egress proxy configuration

.profile
This changeset adds the `no_proxy` environment variable to be set at the time our app runs to exclude the internal apps running within our platform that are handled by Cloud Foundry network policies instead.  Without this in place, the egress proxy will not allow our deployed apps to talk with one another.
- Internal apps within a Cloud Foundry environment can be configured to be able to see and speak to each other via [explicitly defined network policies](https://docs.cloudfoundry.org/concepts/understand-cf-networking.html#securing-traffic) that account for secure container-to-container traffic within the platform.  We want to leverage these for our own apps, but maintain the egress proxy for any traffic going out to external resources.
=> Add no_proxy environment variable

poetry.lock
This changeset updates the notifications-utils library to 0.2.7.
- Keeps our project dependencies up-to-date.
=> Update notifications-utils to 0.2.7

app/aws/s3.py, tests/app/aws/test_s3.py
This fixes the problem that was seen by one of our users today for sure (we used a modified version of their csv to test with).  It is a good bet that this is the same problem the other user saw.
The only potential problem with this fix is if someone did something crazy like:
backup phone number, phone number, name
In which case we would end up sending to the backup phone number.  But it seems like we could have a rule that only one phone number is specified.
=> handle bom in phone number field

app/aws/s3.py, tests/app/aws/test_s3.py
This is a one-off production deployment for the API to fix the parsing of CSV header rows for CSVs that are encoded with the `utf8bom` character set (UTF-8 with byte order marks).  It also includes a fix for a log statement to be a proper `f''` string (formatted string).
- https://github.com/GSA/notifications-api/pull/785
- https://github.com/GSA/notifications-api/pull/779
- There are no changes to the actual CSV processing for the batch notifications, just how the header row is read.
- The log statement fix ensures our application log entries are formatted properly.
=> One-off API Production Deploy to fix CSV parsing issue - 02-02-2024

poetry.lock
This changeset updates notifications-utils to 0.2.8 to address a cryptography dependency update and Dependabot security alert.
- Addresses a Dependabot security alert and keeps our project dependencies up-to-date.
=> Update utils to 0.2.8

.github/pull_request_template.md
This changeset adds a template to the repository for our pull requests.  The intention is two-fold:
- To make it easier to know what information and details to include in our pull requests
- To improve the quality and usefulness of our pull requests
This is a start and we will be adjusting this over time as we learn more and refine our process.
- This will help make sure we capture relevant information and details from a security compliance perspective in future pull requests.
=> API:  Add a pull request template

docs/all.md
This changeset adds documentation for what to expect and how to conduct and receive code reviews.  We want to improve our team practices and ensure that all members know how to engage and what to expect with code reviews.  Furthermore, this can serve as another model and positive example of how to collaborate as a team in the broader open source community.
- The documentation makes explicit mention of looking for security compliance concerns and documentation in future pull requests and code/system changes.
=> Add code review documentation

docs/all.md
This changeset adjusts the language slightly to use clearer terms for the individuals involved in a code review.  Specifically, it changes the word `reviewee` to `author`, meaning the person(s) who created the pull request and/or wrote the code.
- None; this is a minor public documentation update.
=> Update reviewee to author in the code review documentation

poetry.lock
*A note to PR reviewers: it may be helpful to review our
[code review documentation](https://github.com/GSA/notifications-api/blob/main/docs/all.md#code-reviews)
to know what to keep in mind while reviewing pull requests.*
This changeset updates the version number of the notifications-utils library to `0.2.9` to account for a recent update to the `cryptography` module.
- Closes out a few Dependabot security alerts and corresponding `pip-audit` alerts.
=> Update utils to 0.2.9

app/aws/s3.py
Previously we were showing a long error message if we knew the CSV file blew up, otherwise if we could not get the phone number we showed 'Unknown Phone'.  Standardize on 'Unavailable'.
N/A
=> If phone number is unavailable, change text to 'Unavailable'

app/dao/date_util.py, tests/app/service/test_statistics.py, tests/app/service/test_statistics_rest.py
Changed logic in `get_months_for_financial_year(year)` to return the months before `now` like a calendar year instead of the logic that was in place for the UK's financial year.
None
None
=> Returned months changed to calendar year

README.md, docs/all.md
This changeset adds a bit of missing information to our README and documentation for E2E test configuration.  This is required for the project to be set up correctly, and while it will work out of the box, there are a couple of adjustments that need to be made to ensure everything is configured correctly.
- Adds publicly available documentation to make sure that local environment variables are set correctly.
=> Add E2E configuration information to docs

app/organization/invite_rest.py, tests/app/organization/test_invite_rest.py
This PR addresses the issue found on staging, when inviting a user through the organization invite path the email has personalisation saying "The GOV.uk team...". It's a hardcoded string so it will now say Notify.gov team.
My only question is what do we want the email to say if not "Notify.gov team"?
None
=> Removed gov.uk text from org invite

app/dao/users_dao.py, app/models.py, app/user/rest.py, migrations/versions/0411_add_login_uuid.py, tests/app/dao/test_users_dao.py
Our original implementation of the login.gov integration was keyed off the user's email address.  While this works, it's not best practice because if the user were to change their email address in the login.gov app, we would lose track of said user and they would not be able to log in.
Best practice is to use login.gov's UUIDs for users.  That way if the user changes their email address in login.gov, they can still log into our app.
It's important not to leak info through debug statements.
=> fix login.gov to use user uuid instead of email (notify-admin-1277)

.github/workflows/checks.yml, Makefile
Local testing has been failing for a while because code coverage was below 95% (it was being reported as 93%).
It turns out there are two big discrepancies between local code coverage testing and testing in the cloud.
In the cloud, coverage failed if it was below 50%.  Coverage also EXCLUDED notifications-utils code.
Locally, coverage failed if it was below 95%, but it INCLUDED notifications-utils code.
If we exclude notifications-utils code, the true test coverage is 88%.  So, set the fail threshold in the cloud temporarily to 87%, write a ticket to write more tests, and change the local coverage test to exclude notifications-utils while still failing if below 95%.
N/A
=> fix code coverage reporting

migrations/versions/0410_enums_for_everything.py
This is an effort to correct an issue found in staging. It removes all records in the `service_permissions` table in the database that have invalid permission types assigned to them, right before switching to using the enum type. This should get us past the current blocking problem we're seeing in staging.
Reference: #847
=> [Bug] API-847 - Making the enum migration more smooth.

app/organization/rest.py, app/user/rest.py
When we removed personalisation from the database, it worked fine for text messages, because all text messages were converted into jobs with one code flow and we could therefore always retrieve the personalisation from the CSV files.
However, there are a number of email notifications that do various unusual tasks (reset password, 90 day verification, invites, etc.). These are not jobs and have no CSV file containing the personalisation.  So, we need to put the personalisation in redis so that it persists while the notification goes through the notification queue and awaits sending.
We want to make sure potential PII in the personalizations doesn't linger around in redis forever, so we should use the one hour timeout (ex=60*60) option to make sure redis deletes stuff when it doesn't need …
=> fix email notifications missing personalisation (notify-api-853)

app/service/utils.py, tests/app/notifications/test_validators.py
We recently had a discussion to allow devs to send to the simulated sms numbers while in trial mode. These changes are also further necessary for Cloudwatch alerts testing in staging. 
None. We are using simulated numbers through AWS.
=> Add simulated sms numbers to allow list in trial mode.

poetry.lock
This changeset updates notifications_utils to 0.3.0 to account for other dependency updates.  It also accounts for the removal of Celery in utils.
- Helps keep our dependencies up-to-date to account for security notices.
=> Update utils to 0.3.0

app/aws/s3.py
This changeset removes a couple of debug lines that we had in place from when we switched to processing CSVs for looking at phone numbers.  This has now been proven out, and the additional log entries make it difficult to troubleshoot other issues that may arise.
- None; removal of leftover debugging statements from our logs.
=> Remove debug lines in CSV processing

deploy-config/production.yml
This changeset adjusts our worker process memory to 1G from 512MB in production. We recently saw memory-related crashes for the Celery worker processes, meaning they did not have enough available to them.  This was compounded by an [ongoing platform issue with cloud.gov](https://cloudgov.statuspage.io/incidents/78t5kvrx342z) due to Cloud Foundry VMs operating with a Linux kernel that has a memory allocation issue.
Fixes for the Linux kernel and Cloud Foundry VMs are in flight and cloud.gov is tracking this closely, but we can help ourselves in the mean time and given …
=> Adjust production worker memory to 1G

runtime.txt
This changeset updates the runtime.txt file so that Cloud Foundry picks up Python 3.12.x instead of Python 3.9.x.
- Brings us to the current latest and greatest stable of version of Python!
=> Update Cloud Foundry runtime.txt file

README.md
Update the README to specify the org `gsa-tts-benefits-studio` and space `notify-local-dev` in the instructions for the `cf login` command
=> Add cf org and space to README

app/config_files/templates.json
1. Change the link to [Join Organization](((url)))
2. Run `poetry run flask command update-templates`
3. Look in database and see that the organization invite has actually changed to what we want
4. Login in to app and issue an organization invite --- No Change!
I looked at send_to_providers.py and there's all this caching and template manipulation going on in notification_utils, sigh.  How do we clear this cache?
N/A
=> Fix organization invite template

app/dao/users_dao.py, app/user/rest.py
Originally login_dot_gov was handling sign in where we expected existing users to be in our database, and login_dot_gov was just providing the authentication.  With the new registration workflow, users may not actually exist in our database when they are invited.  So if we cannot find a user in our database, we have to return empty json and allow the Admin app to figure out what it's trying to do, instead of just blowing up because we cannot serialize a None object.
N/A
=> return None to handle new user

app/organization/invite_rest.py, app/service_invite/rest.py
Remove debug statements
Remove debug statements.  I'm trying to use the 'hilite' function copied from admin project to make it easier to find debug that is meant to be temporary.  Searching on 'print(' brings up all the Blueprint hits.
=> remove debug

docs/all.md
Apparently this error is common:
```
FATAL:  database "test_notification_api" does not exist
```
In lieu of getting to the bottom of it, add a note about how to fix it
=> Add a note about how to resolve db error

terraform/demo/main.tf, terraform/demo/providers.tf, terraform/production/main.tf, terraform/production/providers.tf
This changeset reverts a few of our recent changes to the production and demo Terraform files to re-enable deployments.
We are working through fixing this and will re-introduce these changes once we figure out how to get the changes to properly work (which are tied to the infrastructure checks as well).
- This will re-introduce several deprecation warnings in the infrastructure verification checks, but they will be non-blocking.
=> Revert recent Terraform changes to prod and demo

docs/all.md
The command `createdb test_notification_api` is a prereq to running `make test`. Clarify that it is necessary, not just a troubleshooting step.
=> Move createdb step

app/config_files/templates.json
Small content update to the email a user gets when signing up for the Notify service to let them know they'll have to use Login.gov to sign in
=> 1270 update email content

sample.env
Add/fix necessary environment variables to run login.gov in local dev environment.
N/A
=> add login.gov env vars to sample.env

app/job/rest.py, poetry.lock
After the message is sent, the UI display changes from a preview of the message, to the actual message that was sent.  This involves a call to the backend.  In that call, personalization was not attached properly and hence the UI never got it.
N/A
=> fix personalization on job/service/notification api

poetry.lock, pyproject.toml, tests/conftest.py
Installed the python library sqlalchemy-utils which contains the methods database_exists, create_database, drop_database. I modified the _notify_db method in conftest.py to allow for the method to check if the test_notifications_api db exists, if it does it will create it. After all tests run and during deconstruction, the _notify_db method will then remove the test_notifications_api database as part of it's cleanup. 
This should include:
- Links to issues that this PR addresses
https://github.com/GSA/notifications-api/issues/598
- Screenshots or screen captures of any visible changes, especially for UI work
NA
- Dependency changes
Added sqlalchemy-utils to poetry lock
NA
=> Added ability for poetry to add and delete the test_notifications_api db during tests for #598

app/celery/scheduled_tasks.py, poetry.lock, tests/app/celery/test_scheduled_tasks.py, tests/app/user/test_rest_verify.py
The write-up for this ticket was done at the time when we still had phone numbers in the db, and were trying to be alerted when the number of phone numbers in the db approached 10,000.
(Recipient) phone number have been removed from the database, so there is no longer a need for this notification.  It's been removed, along with the scheduled, and some tests were fixed that were mocking the wrong redis call (but still passing somehow).
N/A
=> remove deprecated notification

.github/workflows/checks.yml, poetry.lock
This changeset updates a couple of dependencies, including our Python dependency audit check, and specifically ignores a gunicorn audit flag that appeared on 4/16/2024.
As soon as there is an update available for gunicorn that addresses the issue we will remove the flag to ignore the vulnerability report and update the dependency.
- We are explicitly telling the `pip-audit` GitHub Action to ignore a reported `gunicorn` vulnerability that doesn't have a current fix available at this time.  As soon as one becomes available, we'll remove the ignored vulnerability report …
=> Updated dependencies and ignore gunicorn audit flag

app/config.py, poetry.lock
The previous attempt to remove the deprecated check-db-notification-fails task was incomplete, leading to an attempt to run a non-existent task, resulting in an alarming looking but essentially harmless error in the logs.  So remove it completely.
N/A
=> remove check-db-notification-fails task from schedule

app/dao/users_dao.py
The db check between what we had stored in the users table and what was coming from login.gov was case sensitive, and people seem to write their emails differently for different apps.
N/A
=> make email_address check case insensitive

app/service_invite/rest.py, tests/app/service_invite/test_service_invite_rest.py
We need more visibility into what is going wrong with redis.  Use raw_set and raw_get which are not wrapped and will raise Exceptions, etc.
N/A
=> use raw_get and raw_set for better debug of redis

app/service_invite/rest.py, tests/app/service_invite/test_service_invite_rest.py
Add an API to return the service invite data from the API server's redis cache.  Add a couple tests as well.
N/A
=> api to return service invite info

terraform/bootstrap/providers.tf, terraform/demo/providers.tf, terraform/development/providers.tf, terraform/production/providers.tf, terraform/sandbox/providers.tf, terraform/shared/egress_space/providers.tf, terraform/shared/ses/providers.tf, terraform/shared/sns/providers.tf, terraform/staging/providers.tf
Upgrade patch version of CloudFoundry Terraform provider to [v0.53.1](https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/releases/tag/v0.53.1)
Ideally I would do this a single environment at a time. Unfortunately, this PR upgrades across all environments! The reason is the `shared` module.
When a module uses the `shared` code, it they must both use the same version of CloudFoundry. In order to update one environment module (like `sandbox`) I must update `shared`, and thus I must update all modules so their reliance on `shared` does not cause a version mis-match.
⚠️ This change should be deployed to lower environments and validated before being deployed to production. It will change Terraform configuration of *all* environments to which it is deployed.
=> Upgrade cloudfoundry from 0.53.0 to 0.53.1 everywhere

README.md, terraform/README.md, terraform/bootstrap/providers.tf, terraform/demo/providers.tf, terraform/development/providers.tf, terraform/production/providers.tf, terraform/sandbox/providers.tf, terraform/shared/egress_space/providers.tf, terraform/shared/ses/providers.tf, terraform/shared/sns/providers.tf, terraform/staging/providers.tf
Update our Terraform version requirement to what our CI/CD is using. This precaution ensures no one develops against an old version with breaking changes.
* Upgrade the minimum Terraform version across the codebase to v1.7.x
* Update the main README to reflect this Terraform version
* 🏆 *Bonus!* Update the terraform dir README with Troubleshooting info on service account permissions
⚠️ This changes the Terraform configuration of *all* our environments. Only deploy to higher environments after the change has been deployed and validated in lower ones.
=> Upgrade terraform version to match CI/CD

terraform/bootstrap/main.tf, terraform/sandbox/main.tf
Upgrade [terraform-cloudgov module](https://github.com/18f/terraform-cloudgov/) from v0.7.1 to v0.9.1 in two locations:
1. `bootstrap` module
2. `sandbox` module
The same change will be made in deployed environments once it is proven in the above.
The terraform-cloudgov module [has an open issue](https://github.com/18F/terraform-cloudgov/issues/35) to remove the deprecated `recursive_delete` argument and replace it with more modern notation. We want to be prepared to make use of this change when it is made, particularly in the `bootstrap` module, where we want to protect Terraform's state bucket. So let's validate the intermediate versions by upgrading now.
Ideally we would use the `prevent_destroy` argument (which is used within the `lifecycle` meta-argument) when we invoke @rahearn's …
=> Upgrade terraform-cloudgov module

app/organization/invite_rest.py, app/service_invite/rest.py, poetry.lock, tests/app/service_invite/test_service_invite_rest.py
The original attempt to implement  service invites via login.gov bypassed most of the logic already contained in InvitedUser, which led to a state where things almost worked if you followed the happy path, but if you did anything unusual you would see weird anomalies.
This PR goes back and re-implements, removing the attempt to use redis to store the invite info.  Instead the invite info is sent out in the login.gov as the STATE parameter, which mimics the previous implementation.
This is not really a security consideration, but feedback from the login.gov team via zendesk support is that, while the state parameter is always returned back unaltered, it might be better to use a session or something to hold the information.  I have two objections to this:
1. Person A is sending an invite …
=> fix service invites

app/service/rest.py
This changeset fixes a recently added debug statement that was assuming a list was not empty, which was causing end-to-end tests to break in the admin site.
- None for this change.
=> Fix debug statement

tests/app/dao/test_service_sms_sender_dao.py
*A note to PR reviewers: it may be helpful to review our
[code review documentation](https://github.com/GSA/notifications-api/blob/main/docs/all.md#code-reviews)
to know what to keep in mind while reviewing pull requests.*
The error was apparently caused by the change to the new not-deprecated method for u
Issue: #1044
Can't think of any.
=> API-1044 - Fixing the test to be less fragile.

terraform/sandbox/main.tf
Upgrade to [version 1.0.0](https://github.com/GSA-TTS/terraform-cloudgov/releases/tag/v1.0.0) of terraform-cloudgov module in the sandbox.
This version removes the deprecated `recursive_delete` parameter. The protection this parameter offered will need to be replaced in the future. Before that replacement is created, there's no harm in eliminating the param from the sandbox Terraform code, where deleting was always allowed.
=> Jskinne3 terraform cloudgov 1.0.0

terraform/sandbox/main.tf
My proposal of how to keep ourselves from destroying Terraform resources on accident: a do-nothing resource with `prevent_destroy` in it. Here in the sandbox it is set to `false` because destroying sandbox stuff is OK. In other environments, it will instead be set to `true`.
This is a replacement for the deprecated `recursive_delete` argument deleted in #1052 
Does this protected `null_resource` thing really protect all the other items in the module? Or will it only protect the useless `null_resource` itself?
Having tested it, here’s how it behaves:
When `terraform destroy` makes a plan that would have destroyed anything containing `prevent_destroy = true` the command halts with this error:
```
│ Error: Instance cannot be destroyed
│
│   on main.tf line 9:
│    9: resource "null_resource" …
```
=> Add a null_resource with prevent_destroy to Sandbox

terraform/sandbox/main.tf
Per issue #978 &mdash; A proposal for how we will upgrade Redis from v6.2 to v7.0. This PR describes a new service instance which can then be bound as the primary Redis for the API app. The old instance would be unbound at the command line and, in a future PR, deleted.
The new resource uses a different name. I _think_ that's fine; requires validation in higher environments. (This is just Sandbox!)
=> Redis upgrade proposal

terraform/demo/main.tf
Per issue #978 and proposed solution in PR #1086
Describe a new service instance to be bound as the primary Redis for the Demo environment, upgrading the Redis version. The old instance will be unbound at the command line and, in a future PR, deleted.
* Redis v7.0
* terraform-cloudgov v1.0.1
=> Demo: Redis upgrade step 1

.github/actions/setup-project/action.yml, poetry.lock, pyproject.toml, runtime.txt
I can't run `make bootstrap` locally if the pyproject.toml is set to "==3.12.3" without upgrading to 3.12.3 in my local environment, so I have set the pyproject.toml to "^3.12.2" and the action is essentially ==3.12.3
N/A
=> pin python to 3.12.3

.github/workflows/deploy.yml
Update the GitHub action [tj-actions/changed-files] from v41 to v44
This is an attempt to fix a problem in which `terraform init` and `apply` are being skipped in [a context where](https://github.com/GSA/notifications-api/actions/runs/9665716279/job/26663508161) we don't think they should be skipped.
The action [has made modifications](https://github.com/tj-actions/changed-files/blob/main/HISTORY.md#4300---2024-03-13) to its `any_changed` function which [we use](https://github.com/GSA/notifications-api/blob/cac5ef7b34f912a5f6f54ebcea91e1ff698b624c/.github/workflows/deploy.yml#L40) to determine when these Terraform commands. So, perhaps upgrading will correct the function's behavior.
This PR only applies to staging -- the staging workflow has the generic name `deploy.yml`. After it is …
=> Upgrade tj-actions from v41 to v44 in Staging

terraform/sandbox/main.tf, terraform/staging/main.tf
The sequel to #1104:
Remove old v6.2 Redis instance, now that new instance has been created and bound, from the Staging and Sandbox environments 
these are the commands that were used to unbind the old and bind the new:
```
cf unbind-service notify-api-staging notify-api-redis-staging
cf bind-service notify-api-staging notify-api-redis-v70-staging
cf restart notify-api-staging
```
=> Staging: Redis upgrade final step

manifest.yml, terraform/production/main.tf, terraform/staging/main.tf
I accidentally created our new v7.0 Redis in prod without the correct plan! So:
* Switching binding (via manifest file) back to old Redis
* Deleting new Redis
This will allow it to be replaced in a subsequent PR
=> Temp switch manifest to old Redis name, delete new Redis block

manifest.yml, terraform/production/main.tf
Restore Redis block that was deleted in https://github.com/GSA/notifications-api/pull/1123 but with the correct plan name
=> Restore Redis instance at v7.0

terraform/demo/main.tf, terraform/production/main.tf, terraform/staging/main.tf
*A note to PR reviewers: it may be helpful to review our
[code review documentation](https://github.com/GSA/notifications-api/blob/main/docs/all.md#code-reviews)
to know what to keep in mind while reviewing pull requests.*
Removing the old, inept version of redis from terraform, as everything is pointing to the new shiny v70.
This is the final part of https://github.com/GSA/notifications-api/issues/978. 🎉 
- We don't want to leave old, unsupported service instances lying around.
=> Removed old redis from terraform.

docs/all.md
The write up on how to run the new download-csv-file-by-name command had the wrong syntax in all.md.  Fix it.
N/A
=> fix command syntax

.ds.baseline, app/dao/services_dao.py, tests/app/dao/test_services_dao.py
There was a simple logic error in the new function for the new endpoints. There also was a lack of unit test, which has been corrected.
This is not attached to any existing card on the board.
None that I know of at this time.
=> Logic fix for new endpoint daterange

terraform/development/main.tf
In local development module:
* Upgrade terraform-cloudgov to v1.0.0 (the latest)
* remove recursive_delete
A fraternal twin of PR https://github.com/GSA/notifications-admin/pull/1742
Both are part of issue https://github.com/GSA/notifications-api/issues/1139
=> Upgrade terraform-cloudgov, remove recursive_delete in dev module

runtime.txt
This changeset modifies the Python version specified in the runtime.txt file for cloud.gov.  The buildpack was recently updated, and the older version we had pinned is no longer supported.
* We need to keep our language stacks up-to-date in order to stay in sync with what the cloud.gov platform supports so that we're staying on top of updates and security-related fixes.
=> Update Python runtime version for cloud.gov

app/models.py, app/service/rest.py
This sets up logging for sender information. It does not contain PII for individuals, it contains information we have for the sender.
=> Getting the logging where I think it will be most useful.

deploy-config/production.yml
This changeset adjusts our production manifest settings to strike a balance with memory usage and app/worker instances.  We are currently running into a memory quota but would still like to increase our memory for improved app performance and stability.
Based on our current app usage, our memory is actually probably fine at 2 GB for now, but we did need to increase the number of worker instances.
* Making sure the apps have enough memory available to them helps keep them stable.
=> Adjust production manifest settings

app/celery/nightly_tasks.py
Set some additional logging where the error is to hopefully capture what job is causing the issue.
None. Just adding something that reveals the affected job number into the logs.
=> API-1130 Logging set-up

terraform/development/main.tf, terraform/production/main.tf
* Delete a `recursive_delete` local var that I missed earlier
* Delete a boilerplate code comment which was misleading because the domain resource is managed in the Admin app instead
=> Cleanup: remove comment unused local var

app/delivery/send_to_providers.py, tests/app/delivery/test_send_to_providers.py
We can check the sender that the notification knows about against the list of available senders for a given service.  If the notification's sender is not on the list, we can raise an exception.
N/A
=> raise exception if phone number doesn't match

notifications_utils/request_helper.py, tests/app/delivery/test_send_to_providers.py
Prevent the stack trace from being dumped in the log.
Prevent information disclosure
=> Exception Investigation: app.authentication.auth:AuthError

app/dao/users_dao.py
The double sort kind of made sense to me in theory, but for some reason it's delivering results different from what I would expect to see.   And so, in thinking more about it, I realized that only developers are going to have users that are part of ten, twenty, thirty services.  All our customers have exactly one service so the sort would not be doing anything useful, anyway.
N/A
=> fix sort on download all users

deploy-config/demo.yml, deploy-config/staging.yml
This changeset adds a bit more memory to the staging worker instance, and it bumps the number of worker instances to 2 in staging and demo.
* This addresses a few memory limits we've been hitting in staging with our API while we're testing the site and trying to replicate a heavier amount of usage.
=> Adjust staging and demo worker instance settings

app/aws/s3.py, app/service/rest.py, tests/app/aws/test_s3.py, tests/app/dao/test_fact_notification_status_dao.py, tests/app/service/test_rest.py
1. Shorten exponential back-off times so that we don't time out just because we're doing back offs
2. Do an initial check to see if it even looks like the job is in the bucket before we start any back offs
3. Use global variable/singleton so we aren't endless recreating boto resources.
N/A
=> improve exponential backoff while job hunting

app/clients/sms/aws_sns.py, app/delivery/send_to_providers.py, app/user/rest.py, tests/app/delivery/test_send_to_providers.py
Previously when the user wanted to change their phone number in the UI, we prompted for their password.  However, now the whole concept of password belongs to login.gov, so we cannot prompt for that.  Eliminate the password step, but there is still the verify code step.  So user will change their phone number, but they have to have access to the new phone number in order to effect the change.
N/A
=> Change phone number in Notify.gov w/o entering password

app/dao/jobs_dao.py, app/job/rest.py, poetry.lock
We have some anomaly where the created_at field for jobs is set 3 days in the past (intermittently).  It seems like there is only one place where this happens (dao_create_job()), so add some debugging and a repair attempt and get this up to staging and see what happens.
We have a couple dozen tests using "freeze time" which all break if we try to do the repair, so do a check on what environment we are running in before doing it.
N/A
=> Fix job.created_at time if necessary

notifications_utils/logging.py
We do some log formatting to prettify the logs, which is great, but the formatting fails if the log message is a nested dictionary, which it is when we get delivery receipts from AWS.  Which means we are getting a stack trace every time a message is delivered or permanently fails.  This serves no purpose, and doesn't affect logging at all (ie, we still get the delivered/failed message, just with extra unwanted stack traces).
Suppress the stack trace if it is caused by a KeyError.
N/A
=> fix log formatting

app/dao/jobs_dao.py, docs/all.md
Avoid any edge cases where the 7 day report might be trying to access data more than 7 days and 0 hours old that has been deleted by the nightly task.
N/A
=> change data retention to 7 days, 23 hours

.github/workflows/deploy.yml, app/commands.py
We found that GitHub does not easily support automatic secret rotation so we are going to do it manually for now.  Create a task that will generate a salt, then the developer of the month will follow the steps in the Google calendar task to complete the rotation.
N/A
=> make generate-salt command

app/aws/s3.py, poetry.lock
Our reports only cover the past 7 days, so there is no need to download and cache jobs that are older than that.
N/A
=> limit cache download by time

app/dao/fact_notification_status_dao.py, app/template_statistics/rest.py, tests/app/dao/test_fact_notification_status_dao.py, tests/app/template_statistics/test_rest.py
Adding the requested fields to the API for the template statistics report.
This also rewrites the queries to use SQLAlchemy 2.0 standards for the modified DAO function.
Ref: #1265 
None I can think of, these aren't protected data in the fields, and if anything, the new SQLAlchemy 2.0 standard will be more future-proof than using the old form.
=> Api 1265 adding fields for template stats

app/authentication/auth.py
Looks like we might be raise a TypeError that gets silently suppressed.  Add more debug around this to get e2e tests working with the staging backend.
Remove this debug when it works.
=> more debug for e2e tests

app/authentication/auth.py
Unraveling what exactly is going on with the auth token on the admin side (doesn't match API side) seems rather involved and may ultimately require that we bring all of notifications-python-client package into our code base, something we'd hoped to avoid.  In the meantime, try to see if we can get e2e tests working by relaxing auth checks on staging tier.
Bypassing auth check on staging tier should be fine, but need to be mindful to never ever allow for all tiers.
=> E2E Test Improvement: leverage the live staging API instead of deploying a local instance in CI/C

app/aws/s3.py, app/celery/tasks.py, app/config.py
We want to delete s3 objects that are more than 7 days old, but the user can schedule jobs up to 3 days in advance, so it's really 10-11 days old (max).  So to be on the safe side, call it for right now 14 days.  If an S3 object is more than 14 days old, we can totally delete it without care.
But for this iteration, let's just log it and see how much is there!
N/A
=> delete old s3 objects

app/aws/s3.py, app/clients/pinpoint/aws_pinpoint.py, app/delivery/send_to_providers.py
1. checking if the phone number was in SIMULATED_SMS_NUMBERS failed, because recipient is not stored with a + sign, but SIMULATED_SMS_NUMBERS has plus signs. Fix that.
2. add more debug statements so we know more easily if it worked or not.
3. Remove an unrelated debug statement in s3.py that got checked in somehow.  It is harmless in terms of PII but leads to huge amounts of logging.
Currently this can only be tested on staging, as only staging (theoretically) has pinpoint permissions.  Testing on local will give an 'access denied'.
N/A
=> further work on phone number validation

app/delivery/send_to_providers.py
We are doing experimental work to validate phone numbers with pinpoint, and right now that validation is limited to AWS simulated numbers only.  Unfortunately, we are also using the AWS simulated numbers for the load test, so load test on staging is broken due to the problems with pinpoint phone validation.
Add a check to make sure we are on the development or test tiers before doing phone number validation.
N/A
=> fix load test

.ds.baseline, app/aws/s3.py, app/config.py, tests/app/aws/test_s3.py
Previously we added this ability in "log only" mode.  On staging we can now see there are lots of old s3 objects in need of deletion and the logging seems to work properly.
Modify the code so it actually starts deleting old objects and enhance the test so it proves only old objects, and not new objects, are deleted.
N/A
=> actually start deleting old s3 objects

app/aws/s3.py
Our previous method of extracting phone numbers from S3 files was too simplistic, since users might include the words "phone number" in custom placeholders.  See notify-admin #1956
N/A
=> fix phone number lookup

.ds.baseline, .github/workflows/checks.yml, Makefile, app/aws/s3.py, app/celery/tasks.py, app/config.py, pyproject.toml, tests/app/aws/test_s3.py
For our jobs cache we cannot use memcached, redis, or the database.  But at the same time our original solution, ExpiringDict, gave us the problem that every new worker spawned required a separate copy of the cache.
Instead use multiprocessing.Manager to create a dictionary in shared memory.
N/A
=> use shared memory instead of expiring dict for jobs cache

.github/workflows/deploy.yml
Deploy keeps failing. Will try with `secrets.ENV_VAR_NAME` with brackets.
Secure secrets.
=> Go back to brackets with secrets. in command

.github/workflows/deploy.yml
This changeset will hopefully fix the reference to the `LOGIN_DOT_GOV_REGISTRATION_URL` env var in the new `cf_command`.
* The value in question is not a secret, unlike the others.
=> Adjust LOGIN_DOT_GOV_REGISTRATION_URL env var in staging deploy

.ds.baseline, app/aws/s3.py, app/clients/__init__.py, app/config.py, notifications_utils/logging.py, tests/app/aws/test_s3.py
Report performance has been a nagging issue ever since phone numbers got moved out of the db.  In anticipation of future scaling needs, two improvements are being made here:
1.  We're going to use the ThreadPoolExecutor to do download content from S3 files concurrently.  This will speed up the cache regeneration task and take some load off the backend.
2.  When we are grabbing content from S3 we are going to proactively pre-process it and put the phone numbers and personalization into the cache in the form of lists.  This will improve processing speed during report generation because we won't have to go row by row and parse the whole job for each phone number and each personalization.
Note: If we exhaust the connection pool, boto3 will start logging warnings to tell us that, and it will …
=> improve report performance

.github/workflows/deploy.yml
This changeset attempts another fix by referencing the environment variable in a different fashion, according to the GitHub docs:
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#example-usage-of-the-env-context
* We're being mindful of the difference between GitHub secrets and public code.
=> One more attempt at fixing the Login.gov registration URL

.github/workflows/checks.yml, Makefile, app/aws/s3.py, app/delivery/send_to_providers.py, tests/app/delivery/test_send_to_providers.py
Some of the work we did for using shared memory and concurrent downloads managed to break personalizations, so fix that here.
Also, stop running coverage on test code.  This means our true level of coverage is 91%.  Temporarily set it to 91% and make a ticket to bring coverage up to 95% ASAP.
NOTE: I made changes to the tests, then I reverted them.  I'm not sure why the formatting looks like that and there is a big diff, but the actual code didn't change.
N/A
=> fix personalization_bug for one-offs

.github/workflows/checks.yml, app/aws/s3.py, app/commands.py, tests/app/aws/test_s3.py
We inherited a way of naming s3 objects which might have been fine in its original context, but is not optimal for AWS.  For S3, we should not be prefixing all of our s3 objects with "service-uuid" because it pushes everything onto one partition, which will affect search speeds as we scale.  Change the name format to "uuid-service"
Note:  This PR is has a matching PR on the admin side.  They should be checked in at the same time.  
N/A
=> optimize S3 partitioning

app/aws/s3.py, app/job/rest.py, app/user/rest.py
Something about the new s3 partitioning approach works fine locally but fails on staging.  Add debug.
N/A
=> debug s3 partitioning

app/service_invite/rest.py
We have to temporarily park some info related to the invite in redis, and I think due to an excess of security thinking, a 30 minute timeout was applied to that info.  But users actually have a whole day to accept the invite.  So I think this bug has been here for a while and we just didn't have any people who dawdled in accepting their invites.  Change the timeout to two days for redis.
N/A
=> Bug: Invites expiring immediately

docs/all.md
Add documentation for how to perform the monthly task to rotate the DANGEROUS_SALT
N/A
=> add documentation for how to rotate DANGEROUS_SALT

.github/actions/deploy-proxy/action.yml, .github/workflows/deploy.yml
This changeset updates the egress proxy deployment steps to match the admin repo, based on lessons learned there.
**NOTE:** Once we get this working, we'll have to uncomment the check for repo changes, as we don't need to deploy this every single time.
* We need to make sure we're able to update the egress proxy to keep our outbound network traffic secure.
=> Update egress proxy deployment steps

.github/workflows/deploy-prod.yml
This changeset fixes the name of the prod space (notify-production).
* We need to make sure we can update and deploy the egress proxy.
=> Fix reference to prod space

app/aws/s3.py
While we transition to the new naming convention for CSV objects, we need to support both formats.  We missed a spot and right now we can't download reports that contain "old" data.
N/A
=> fix partitioning

.github/workflows/checks.yml, Makefile, app/aws/s3.py, app/commands.py, app/delivery/send_to_providers.py, app/service/rest.py, notifications_utils/sanitise_text.py, tests/app/delivery/test_send_to_providers.py, tests/app/service/test_rest.py, tests/app/test_commands.py
Boost code coverage on the API side from 91 to 93 percent.
1. Comment out some commands we are not using at the moment and may not ever use.
2. Write some tests for service/rest.py that were missing.
3. Refactor some code so there is better coverage.
N/A
=> increase code coverage to 93 percent

app/service_invite/rest.py, tests/app/service_invite/test_service_invite_rest.py
Makes nonce opertions for login.gov work for invites as well as the logins now. (api side)
https://github.com/GSA/us-notify-compliance/issues/50
This improves the security for logins through login.gov.
Do not merge until https://github.com/GSA/notifications-admin/pull/2024 is also ready.
=> US-NOTIFY-COMPLY 50: Verify Nonce For Invite

migrations/versions/0044_jobs_to_notification_hist.py
Fortunately our migration scripts never used sqlalchemy 1.4 syntax.  I did fix one instance, but as you can see the migration was already commented out.
I gripped the following patterns to see what needed to be fixed:
.query()
.filter_by()
.filter()
session.query
with_entities()
join()
There were some hits for join() but when I drilled down to the code, these were all string joins to build up lists for raw sql queries.
N/A
=> Upgrade Queries: 7. Refactor Migration Scripts

notifications_utils/logging.py, poetry.lock
The `scrub()` method was restructured to be a function, and then applied to a new custom log formatter.
See: https://github.com/GSA/notifications-api/issues/1328
Scrubbing PII from log entries is very good for security purposes.
=> API-1328 - Using a custom formatter to scrub PII from all log records.

app/clients/__init__.py
We saw some BrokenPipeErrors that caused messages not to be sent.  Some of the stack traces pointed in the direction of multiprocessing.Manager, which handles downloading S3 objects to build up our jobs cache.
One recommendation when seeing BrokenPipeError is to reduce the number of connections in the connection pool, and that is the easiest fix to try.
Others are:
1. Increase memory and CPU
2. Use more retry logic (yuck)
3. Consider replacing multiprocessing.Manager with multiprocessing.Queue or Pipe
NOTE:  The [`multiprocessing.Manager`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Manager) is used in app/aws/s3.py and the whole cache-building workflow also relies on concurrent.futures.ThreadPoolExecutor.  Both rely on the AWS_CLIENT_CONFIG, which defines the …
=> reduce number of pool connections

app/clients/__init__.py
This is changing the `max_pool_connections` after our memory bump, trying to find the right level for application stability.
=> set max_pool_connections to 7

deploy-config/production.yml
This changeset bumps our production app memory for the API to 3 GB available in anticipation of the shift of the job cache being managed by the application itself instead of a worker process.
* This will help keep our API stable by ensuring there's enough memory available.  If we find we don't need it, we can tune it back down in the future.
=> Bump production app memory to 3 GB

app/dao/users_dao.py, app/service/rest.py, app/service_invite/rest.py, tests/app/service_invite/test_service_invite_rest.py
the state was largely unused by our system, and was seen as a necessity for working with login.gov. Now we are checking that the state is correct on return from login.gov. It is sent as a query parameter back from login.gov, and we are now simply checking that it matches a value we have stored in redis.
This also is now generated from the admin, and then passed into the api endpoints for both creating a new invitation, and resending an expired invitation. As such, everything from login.gov is now checked for both state and nonce (the previous work I had done). This will …
=> Verify state for login.gov

app/clients/__init__.py
Reducing the max connection count below the default of 10 seems to be destabilizing.  Put it back to the default.
N/A
=> put max connections back to 10

app/clients/sms/aws_sns.py
Add logging to see what is going on with origination numbers
N/A
=> add debugging for sender numbers

.gitignore, deploy-config/sandbox.yml, docs/all.md, scripts/deploy_to_sandbox.sh
This changeset makes a few adjustments to our sandbox environment config to make the sandbox deployments of the API much easier.  It does this with the following:
* Adds a few environment variable values to the sandbox.yml file to cover the ones that were not there previously
* Adds a new script that can be run in place of memorizing any commands
* Adds documentation on how to configure and run the sandbox environment
* We still need to be mindful of environment variables and not sharing sensitive credentials/secrets.
* This helps make the management of the environment …
=> Make sandbox deployments easier

app/config.py
We set worker max tasks to 20 but this is causing too much worker churn.  Let's try 200 tasks per worker.
N/A
=> adjust worker lifetime

app/aws/s3.py
We cannot download a report with 25k rows, presumably because of excessive logging of INFO level events.  Change INFO to DEBUG.
N/A
=> remove excess log lines from s3

app/config.py
During a load test we observed that memory usage looked pretty stable, but that we were seeing a lot of celery retries.  We think 200 max tasks per worker might be too low of a number and causing excessive churn so bump it up to 500.
N/A
=> Change max tasks per celery worker to 500

terraform/staging/main.tf
Right now we are timing out when we try to read 25,000 notifications from the db in 30 seconds.   But if we want to scale and support more activity, we need to be able to do this.  Try increasing the rds instance size from micro to small in the staging environment.
N/A
=> increase db size from micro to small on staging

app/celery/tasks.py
There was flaw in the logic that inserts notifications into the db.  In the event of a duplicate insert, we were supposed to quit trying immediately.  However, because IntegrityError is a subclass of SQLAlchemyError we ended falling through the catch phase and activating the retry logic.   So we ended up getting 5 copies of the duplicate error in the logs, and because we hit the SQLAlchemyError the whole exception stack trace got printed, which resulted in millions of log lines when we ran a 25k send.
Fix the logic so we exit abruptly on a duplicate insert.  This short circuits the retry logic and results in only one warning level log line.   This, in combination with having each worker support 500 tasks instead of 200 tasks, should reduce the volume of logging from retries by over 90%. …
=> fix notification insert retry logic

app/celery/provider_tasks.py, app/service/sender.py, tests/app/service/test_sender.py
Sometimes at startup one would see an error trying to send an email notification.  The error revolved around the fact that the personalization of the notification was None but there were no details about what the notification was or why this was an intermittent error.
It turns out that when a service goes live, you are supposed to receive an email notification that says "hey, you went live".  This is such a low priority notification that it wasn't really noticeable when it stopped happening, but nevertheless.
N/A
=> fix broken go live email notification

app/celery/tasks.py, app/dao/notifications_dao.py, app/notifications/process_notifications.py
We are getting hammered by duplicate insert/integrity errors.  Change the logic so notifications can only be inserted once.
NOTE:  I tried db.session.merge(notification) and it resulted in hundreds of test failures, unfortunately.  So I went with the clunky approach that doesn't break tests.
N/A
=> change create notification to only insert once

.github/workflows/restage-apps.yml
This changeset updates our restage workflow and GitHub action to use the latest version of the cg-cli-tools to help prevent future issues with performing restage actions for our apps.
* Helps keep our third-party tools up-to-date.
=> Update restage workflow to use latest cg-cli-tools

terraform/production/main.tf
This changeset boosts our production Redis configuration to the 5node-large plan to give us a bit more wiggle room for heavy production workloads.  This should still keep us in the threshold of the second block of 10 nodes we are already signed up for as we currently have 12 nodes going across all environments at the moment.
* Boosting the amount of resources available for our backend services should help keep the application stable as we scale it.
=> Bump production Redis plan to 5node-large

terraform/production/main.tf
Changing the Redis plan in place is not supported - we would need to create a new cluster and then remove the old one.
* N/A with this change.
=> Revert Redis plan back

app/celery/process_ses_receipts_tasks.py, app/celery/provider_tasks.py, app/celery/tasks.py, app/config.py, tests/app/celery/test_provider_tasks.py, tests/app/celery/test_scheduled_tasks.py, tests/app/celery/test_tasks.py
In doing some high volume testing, we discovered that things being placed in redis under the 'retry-tasks' and 'database-tasks' keys were never getting expired.  As a result redis ran out of memory and the whole app crashed and was unrecoverable until we did a purge of retry-tasks.
Set a default expiration time of 8 days.  8 days is probably unnecessarily long and can be revisited in the future, but will address the issue of redis filling up for the near future anyway.
N/A
=> add expire times for redis objects

app/celery/provider_tasks.py
We observed that our old retry schedule for checking delivery receipts (every 5 minutes for 4 hours), while it generally lead to speedy results for small runs, causes a huge amount of throttling for big runs.
As part of scaling and taking into account that carriers may not respond for up to 24 hours, check every hour and add a jitter factor to retries to stagger the timing.
N/A
=> change retry schedule

app/clients/cloudwatch/aws_cloudwatch.py, app/config.py
We are still suffering from periodic celery retries with can cause IntegrityErrors and such.  Since we currently see no signs of resource leakage, increase worker_max_tasks_per_child from 500 to 2000, which should cut retries by 75%.
N/A
=> change worker_max_tasks_per_child to 2000

migrations/versions/0413_add_message_id.py
Our original implementation of checking delivery receipts sent each request for a delivery receipt to a celery task, which made its own call to boto3 logs filter_log_events.  While this was very pythonic and celery-friendly, as we scale it is going to be a bottleneck.  AWS throttles the call to filter_log_events every time it exceeds 5 times per second,  If we have two users doing big runs, that will essentially be all the time.
We are going to refactor this functionality, and start by saving the message_id to the notifications table in the database.  We will then have a scheduled task that makes one call to filter_log_events every five minutes, and processes ALL delivery receipts for all services at the same time, using message_ids, which will identify individual notifications.
N/A
=> add message_id column to notifications

app/celery/provider_tasks.py, app/dao/notifications_dao.py, app/delivery/send_to_providers.py, app/models.py, tests/app/celery/test_provider_tasks.py, tests/app/delivery/test_send_to_providers.py
Start writing message_ids to the new message_id column in the notifications table.
I verified locally this writes message_ids to the notification table.   We'll use the message_ids to map delivery receipts to notifications.
N/A
=> start writing message ids to the notifications table

app/aws/s3.py, tests/app/aws/test_s3.py
Census uploaded a file which looked okay to visual inspection but was reported as corrupt.  It turned out there was a BOM at the start of the file. We thought we were handling it already but we ignored the case where phone number is the only column.
N/A
=> fix census BOM error

app/__init__.py, notifications_utils/logging.py
We found that the celery workers are writing to logs for themselves and then propagating the message again to the main log, resulting in many duplicate log entries.  Stop this propagation.
N/A
=> stop workers from propagating logs

app/celery/tasks.py, app/config.py
To keep Redis from filling up, eject tasks as soon as they complete.
N/A
=> remove tasks from redis after they complete

app/celery/scheduled_tasks.py, app/celery/tasks.py, app/dao/notifications_dao.py, app/notifications/process_notifications.py
This is an effort to fix the integrity error failures we are seeing. If this situation is encountered, it checks to see if the record already exists in the DB. If it does, instead of writing it and then getting the updated notification entry from the DB, it just loads the record from the DB and then continues on.
This is an effort to reduce the load on the celery tasks, and prevent a situation that would always cause a failure from "failing", because it can be continued. A more stable app is a more secure app.
=> API-1466 - Fixing database IntegrityError failures

app/celery/tasks.py
Attempting another IntegrityError fix, by simply ending the task rather than continuing it.
None I can think of.
=> Fixing IntegrityError problems, again.

app/celery/scheduled_tasks.py, tests/app/celery/test_scheduled_tasks.py
During load testing we found that the scheduled check_job_status tasks assumes that any job that started between 30 and 35 minutes ago and has not finished is 'incomplete' and it will kick off and try to complete this job from what it thinks was the last place the job ran.
In practice what happened during the load test was that the job was almost finished (it had been running for 30 minutes and sent more than 9000 of the 10000 messages), but that the check_job_status declared the job incomplete, somehow determined that it should resume from row 5525, and then started trying to save 4000+ notifications to the db that were already there, resulting in IntegrityErrors and multiple retries and a long period of chaos where the db was being hammered, etc.
So for the short term, avoid changing …
=> change time range for incomplete jobs

app/delivery/send_to_providers.py, app/models.py
We previously saw a bug where we were trying to set created_at to "now" in the Job class and while that worked most of the time, some time it set the time to 72 hours in the past, resulting in data missing from the seven day reports.
We have an issue for some time where messages sometimes go out with the wrong sender phone number.   It has been very mysterious and hard to debug.   The data in the db looks correct.  We can look in the UI and see the numbers assigned to every service, so what could be going on?
Well, if you look at what this code was trying to do, it seems like the original form was just pulling all sender phone numbers in the service_sms_sender table and relying on some kind of sqlalchemy magic to limit the result set to the numbers associated with the service in question. …
=> the way we set the sender phone number is very questionable

app/celery/scheduled_tasks.py, app/config.py
This change lowers the task schedule time in `config.py:process-delivery-receipts` from 8 min to 2 min. It will also lower the time chunk size in `scheduled_tasks.py:process_delivery_reciepts()` from 10 min to 3 min. I tried this out locally with a few load test of about 500 each send. There was little lag on the UI for messages stuck in the pending state. This could be tested in staging as well with a full load test.
=> Change delivery receipts tasks time to help UI lag

app/dao/notifications_dao.py
In order to do bulk updates we need the primary key for the notification table (notification.id), which we currently do not have.
Right now we are doing batch updates, which seem to work great.  But the question is how much can they scale.  If they can't scale, we have to switch to bulk updates which requires running a query to fetch all the notification_ids, or storing all the notification_ids in redis.
Add a debug statement to see the elapsed time of each batch update.  Currently we are doing batch updates of 1000.  If the time for the query is 200 ms, we can process 2500 records or so per second, which is 150k records a minute, which is nuts because right now we are doing far less than 1000 records a minute.  Conversely, if the time for the query is 2 minutes we need to start switching …
=> Evaluate Batch Updates versus Bulk Updates

.github/workflows/daily_checks.yml
This changeset updates the reference of the upload_artifacts action from GitHub to be v4 instead of v3. v3 is being deprecated at the end of January 2025.
Thank you @rahearn for the catch on this!
* Keeping our dependencies up-to-date makes sure our application stays secure and functional.
=> Update daily_check GitHub Action

app/celery/scheduled_tasks.py, app/config.py, app/dao/jobs_dao.py, app/dao/notifications_dao.py, tests/app/dao/notification_dao/test_notification_dao.py
If 72 hours have passed and a notification is still in PENDING state, change to FAILED and use Technical Failure for the carrier response so the issue can be seen in reports.
N/A
=> cleanup pending notifications

manifest.yml
Our celery configuration was mostly default settings.  Default settings are for apps that are cpu-bound, but ours is io-bound.   For the case of the --prefetch_multiplier, this is talking about how many tasks each thread can hold onto while it is doing its thing.  The more tasks that a thread holds onto, the more memory is used and more latency is potentially increased.  The optimal value for io-bounds is supposed to be 1 or 2, whereas the default is 4.
N/A
=> set prefetch multiplier to 2

app/dao/notifications_dao.py, app/service_invite/rest.py, tests/app/celery/test_reporting_tasks.py
There have been instances where SQLAlchemy does some funky magic and sets the created_at times prior. We think this could be the issue with invites expiring mysteriously. The invite path leads through here so we add some debugging logic and update the created_at stamp if necessary.
Added some error handling because persist notification is called in quite a bit of different paths, so the created_at value is passed through in different forms. This fixed the issues I was having with tests being broken.
*During local testing, I have not been able to reproduce an invite …
=> Invite expiration fix

app/aws/s3.py, app/config.py, notifications_utils/s3.py, tests/notifications_utils/test_s3.py
boto3 clients and resources are thread safe and have built in connection pooling, so we should reuse them as much as possible.  Implement the singleton pattern to make sure we are doing so.
N/A
=>  make sure we reuse boto3 clients and resources

docs/adrs/0010-adr-celery-pool-support-best-practice.md, docs/adrs/0011-adr-delivery-receipts-updates.md
When moving away from collecting individual delivery receipts, we had to choose between batch updates and using bulk_update_mappings().  We chose batch updates.  Document why.
N/A
=> bulk_update_mappings adr

.github/workflows/checks.yml, .github/workflows/daily_checks.yml
This changeset updates our GitHub Action for dynamic scans to use the latest release of the zaproxy-api-scan.
* We need to keep our security scans up-to-date to ensure our system remains safe.
=> Update zaproxy-api-scan GitHub Action reference

app/commands.py
As we continue to investigate the 'wrong sender phone number' issue, add a command so we can inspect the values in the service_sms_senders table in the database.
- The numbers being retrieved are public numbers, as they are the ones that the messages come from.
- This command can only be run on machines by folks who have access to the information (or locally for development purposes, with test data), and/or in the environment in which the app itself runs.
=> Make a command to see a service's sms sender phone numbers

app/aws/s3.py
On 2/19 at 2:30 ET we encountered a large set of error logs related to a corrupt csv file.  The existing logging did not allow us to pinpoint the file in question.  In addition, the logging that was there logged an error for every corrupt row in the file (and if one is corrupt they are probably all corrupt).
#1 add the service_id and job_id to the log message so we can look up the csv file when this happens.
#2 if one row is corrupt, assume all rows are corrupt and exit the loop.  This is a reasonable assumption as the underlying issue is probably inability to find the "phone number" column due to user error or illegal characters or something of that nature, rather than just one bad row.
N/A
=> improve error handling around corrupt csv files

Makefile, app/dao/date_util.py, app/dao/services_dao.py, app/service/rest.py, tests/app/dao/test_date_utils.py, tests/app/dao/test_services_get_specific_hours.py
This is for issue: [#2204](https://github.com/GSA/notifications-admin/issues/2204)
Related to PR - [2362](https://github.com/GSA/notifications-admin/pull/2362)
- Optimized `/service/{id}/statistics/{start}/{days}` to only return hourly stats for timestamps that exist, reducing unnecessary empty data.
- Removed the previous approach that included all hourly timestamps, ensuring a cleaner and more efficient response.
- Improved grouping logic to correctly associate notifications with their respective hour while maintaining accuracy.
- Refactored date calculations for better readability and accuracy.
- Updated test coverage to handle various scenarios, including edge cases for missing timestamps, different time ranges, and data queries.
This will allow the front end to convert each record to …
=> Updated endpoint to allow hourly updates to enable utc => local time conversion

.github/dependabot.yml, .github/workflows/dependabot-auto-merge.yml
We want to allow dependabot to merge automatically for minor version updates that have PRs that pass all our tests.   In order for this to work, in addition to this code change, we have to make two Settings changes in GitHub:
1. General->Pull Requests-> allow auto-merge
Originally I was going to have the auto-merge script approve the review, but since human PRs require 2 approvals and its not possible to account for that in the Settings, I have changed the script to use the --admin flag, which should be able to merge the script with no reviews.  The 'review' will be the fact that the build passed (branches still have this protection in place).
TODO:
When this is merged, the next dependabot update that comes around should theoretically get auto merged.   Wouldn't that be nice if it worked …
=> enable dependabot auto-merge magic

.github/workflows/restage-apps.yml
The restage command was not picking up changes to environment variables.  Explicitly push the manifest file to reload the environment variables before doing the restage.
N/A
=> do a manifest.yml push to load new env variables

.github/workflows/restage-apps.yml
The previous approach didn't work.  Do `cf push` with the app name (ie notify-api-staging) and specify the manifest file as what is in the deploy-config folder (for example, deploy-config/staging.yml).
N/A
=> revert to using cf push

.github/workflows/restage-apps.yml
The restage action never pulled new environment variables, that is not part of what restage does in the Cloud Foundry system.  We lived with this for two years, and when we wanted to updated environment variables we would just do a deploy.   Ultimately, this was a hassle.
To fix, we looked at `cf push` with the manifest.yml file, but for some reason the file could not be found in the cloud foundry space.  Therefore, we switched to `cf set-env` and just update the handful of environment variables that we have.
N/A
=> Use cf set-env to update environment variables on a restage

app/delivery/send_to_providers.py
Some regression took place where escaped parentheses (%5B, %5D) are being placed around the redirect_uri, resulting in login.gov claiming it is invalid.   For now, strip them right before we send the email.   
N/A
=> fix invites

Makefile
This changeset adds a bit of extra support to the `bootstrap` command to make sure that pre-existing `git` hooks do not interfere with the installation of the `pre-commit` `git` hooks.
* This change allows us to use multiple audit/security tools that hook into `git` without them conflicting with each other.
=> Update Makefile to handle pre-existing git hooks

README.md, docs/all.md
This changeset adds a bunch of new information on how to manage environment variables and credentials in our application.
* No specific security details or credentials are shared; only information already publicly viewable via the source code is referenced.
=> Expand the credential/secret rotation runbook

app/aws/s3.py, app/celery/tasks.py, app/clients/cloudwatch/aws_cloudwatch.py
The regenerate_job_cache() method, which has worked fine for about year, is not raising an exception that talks about not using blocking functions.  The exceptions are not pointing to our code but rather to eventlet underneath.
So, take a guess that there was a latent problem sitting there in the blocking calls to time.sleep() that we make, but that previous versions of gunicorn or python or eventlet (or whatever dependency got updated) were more forgiving and later versions have become stricter.  Replace time.sleep() (blocking) with eventlet.sleep() (non-blocking) and hope the problem goes away.
N/A
=> try to replace blocking sleep call with nonblocking sleep call

app/aws/s3.py, tests/app/aws/test_s3.py
Add the AWS config to the s3 client.  I think this  probably worked prior to the switch over to the FIPS endpoint, and then broke at that point.  Just hoping it works now.
N/A
=> switch to fips endpoint

.ds.baseline, .github/workflows/checks.yml, .github/workflows/daily_checks.yml
This changeset updates the PYSEC notices to ignore due versions that either cannot be fixed or are false positives.  Specifically, this changeset removes previously ignored vulnerability reports and adds PYSEC-2023-312 to the list because it is a false positive and refers to Redis itself, not the Python Redis client (see https://github.com/pypa/advisory-database/issues/237 for details).
* We should only ignore vulnerability reports when it is safe to do so.
* We should remove the ignore flags once the vulnerability is remediated or confirmed to be a false positive.
=> Updated pip-audit ignore-vulns

.github/workflows/checks.yml
This changeset fixes an oversight where a vulnerability got added back to our ignore list.
* We should only ignore vulnerabilities when they're reported when there's a legitimate need or they're a false positive.
* We need to keep this list-up-to-date.
=> Remove extra vulnerability from our ignore list

.ds.baseline, .github/workflows/checks.yml, .github/workflows/daily_checks.yml, app/notifications/sns_cert_validator.py, poetry.lock, pyproject.toml
The oscrypto dependency is no longer being maintained.
It turns out, we only use it for one call -- a call that can be replaced with a call to the cryptography package, which we also have in our project.
Improves security by getting rid of a dependency that is not being maintained.
=> get rid of oscrypto

.ds.baseline, .github/actions/deploy-proxy/action.yml
This changeset unpins the egress proxy release now that we have resolved the other issues surrounding the connectivity to S3.
* We want to make sure we're able to keep the egress proxy up-to-date.
=> Unpin egress proxy release

manifest.yml
This changeset adds an additional environment variable to enforce usage of the correct CA certificate in case any libraries override it.
Please see https://cloud.gov/docs/management/container-to-container/#addressing-certificate-validation-errors for more details.
* We want to make sure the proper certificates are used on the server side.
=> Add one more cert environment variable

.github/actions/setup-project/action.yml, README.md, poetry.lock, pyproject.toml, runtime.txt
Rollback to python 3.12.2 due to unfixable certificate issues.  Keep the improvements we made like getting rid of the oscrypto package.
The way python 3.12 handles certificates is less secure than how 3.13 handles them, but we don't have a choice at the moment.
=> Python manual unwind

app/config_files/templates.json
Add a warning to invitations that user should log out prior to accepting.
NOTE: it's necessary to run the update-templates command to update this template on the various tiers
N/A
=> add warning to log out before accepting invite

app/dao/jobs_dao.py, app/dao/notifications_dao.py
A few months ago we found that sometimes when jobs and notifications are created, the 'created_at' field is 'magically' set to the wrong time by sqlalchemy.  Whatever problem is happening is deep in the heart of sqlalchemy and not in our code, and we have added repair code to fix the time if it's wrong, but unfortunately we also put some debug statements in at 'error' level.
This makes it difficult to search the logs for real errors.  For example, on production currently there are a couple of hundred 'errors' for the past 24 hours, but as far as I can tell they are all these wrong time things, which we already have work arounds in place for.
Demote these log messages to 'warning' so it's easier to search for real problems.
N/A
=> clean up logs

app/celery/nightly_tasks.py, app/config.py
Cronitor only runs on production.  In the production logs as of 7/8/2025 we were seeing the following error:
Cronitor enabled but task_name remove_sms_email_jobs not found in environment
This particular task is set up the same way as other tasks that do work, and cronitor on production is apparently using auto-discovery.   So the hypothesis is that the use of underscores in the task name is causing the problem.  All the working tasks use dashes.  This is at least a theoretical problem with cronitor, wherein both _ and - are theoretically allowed but auto-discovery could mess up with underscores.
So we can push this change to production and see if the problem is resolved.
N/A
=> fix cronitor task name

Makefile, app/aws/s3.py, app/celery/tasks.py, app/clients/cloudwatch/aws_cloudwatch.py, manifest.yml
There's an incompatibility between our use of eventlet on the one hand, and starting up celery with pool=threads on the other.
Sounds like the python world is moving away from eventlet in favor of asyncio, and in the long run we might want to consider that.   But in the short run, let's just stabilize things in eventletland.
Set pool=eventlet, up the concurrency, and change time.sleep() to eventlet.sleep()
There are still a couple of possible blocking things in our code (serialized_models uses Threading.RLock, which doesn't sound good) but hopefully these changes reduce the frequency of the conflicts at least.
N/A
=> Celery tasks

gunicorn_config.py
Eventlet monkey patching has to happen before any major libraries are imported, otherwise we could be running with the original os or socket, which may block the main eventlet loop.
N/A
=> fix monkeypatching

app/template/rest.py
There was an error showing up in the logs that SMSMessageTemplate does not have the field 'subject'.  I looked in the models.py, and that is correct.  Only Emails have subjects.
N/A
=> fix minor bug where subject is missing

poetry.lock, pyproject.toml
Revert pip-system-certs because it is broken.  It is recommended to use truststore instead.
N/A
=> revert pip-system-certs

app/dao/inbound_sms_dao.py
We are getting a sql alchemy warning currently in the logs:
home/vcap/app/app/dao/inbound_sms_dao.py:131: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
So tidy that up.
N/A
=> clear up sqlalchemy warning

gunicorn_entry.py, poetry.lock, pyproject.toml, scripts/migrate_and_run_web.sh
We are having certificate errors with our python 3.13 upgrade.  In spite of the fact that we are monkey patching gevent at the top of a new gunicorn_entry.py file, there remains that fact that our app has to work with newrelic, and new relic may be messing things up for us as currently configured.
Move the instantiation of the newrelic agent from out in our script, into gunicorn_entry.py.  This ensures that gevent monkey patches everything before new relic starts running.
N/A
=> try initializing new relic after we monkeypatch

app/aws/s3.py, tests/app/aws/test_s3.py
We originally tried to make cache generation run concurrently with ThreadPoolExecutor and it was horribly unstable.  Now that we moved to gevent, lets use gevent.spawn()
In my local testing, we can now generate a cache of 2400 items in ten seconds.
N/A
=> use greenlets for cache generation

app/aws/s3.py
Fix a race condition in the cache handling that caused the cache to occasionally burst into flames.
The key fix is moving "with job_cache_lock" up several lines.
N/A
=> fix race condition

app/dao/jobs_dao.py, app/job/rest.py
This PR adds an option to filter jobs by the time they actually ran (processing_started) instead of when they were created. By default, the query filters by `created_at` but displays processing_started on the activity page, which creates a mismatch. Adding this new parameter will allow the front-end to filter by `processing_started` time on the Activity Page.
related admin pr: https://github.com/GSA/notifications-admin/pull/2815
=> add the ability to query jobs based on processed started time rather than created_at

manifest.yml
This changeset increases our allocated disk quota for the API to be 2G instead of 1G to ensure the app can be fully deployed.
* None; we need to make sure we can deploy our app.
=> Increase our disk quota in Cloud.gov

app/models.py, tests/app/dao/test_service_email_reply_to_dao.py, tests/app/webauthn/test_rest.py
The issue originally reported almost 2 years ago was that the Notification.updated_at field was updating continuously, and the change in the value had nothing to do with when the object was actually updated.
I'm not seeing that now -- not reproducible.
However, setting:
onupdate=utc_now()
instead of 
onupdated=utcnow
means that the value gets fixed at the time the models classes load, and then stays frozen, which is not what we want.  So fix that.
N/A
=> fix updated_at

app/template_folder/rest.py, app/template_folder/template_folder_schema.py, tests/app/template_folder/test_template_folder_rest.py
- Only the user who creates the folder and platform_admin gets default folder permissions
- Folders are private by default, others must be manually added
Related admin branch: https://github.com/GSA/notifications-admin/pull/2841
Issue: Bug: When a new template folder is added, existing users are automatically given permission to it
[#2795](https://github.com/GSA/notifications-admin/issues/2795)
=> Only the person who creates the folder and admin gets default folder permissions

app/celery/tasks.py, tests/app/celery/test_tasks.py
The fix:
- When no notifications exist for a report period, the stale report file is deleted from S3
- This prevents users from downloading outdated data
=> Added code to delete files that are stale

terraform/demo/main.tf
The AWS regions for the SSBs in the demo environment were incorrect; this should fix them and get things working properly with the brokered SNS and SES services.
* None; this a fix to AWS region references.
=> Fix Demo environment SSB AWS regions

terraform/demo/main.tf
After double checking the configuration of the Notify SSB and how the brokerpaks are used with it, the configuration of demo should actually match that of our staging environment, not production because the demo environment is using the staging SSB.  This changeset updates the Demo SSB configuration to match that.
The reason for this is because the staging SSB is deployed into the corresponding staging AWS account, _not_ the demo AWS account.
* None; this is correcting an error with our Demo environment SSB configuration.
=> Update Demo SSB References Again

terraform/demo/main.tf
Changing the region results in Terraform not wanting to apply the change, so back this out for now while we figure out how to fix this to get the Demo site working again.
* None; reverting to previous configuration.
=> Revert Demo SSB SNS change

app/aws/s3.py
Handle StopIteration in extract_phones when CSV files are empty/missing
When users view old jobs, the code crashes trying to read deleted CSV files.
17:35:14.970: [APP/PROC/WEB.1] {"name": "app", "levelname": "ERROR", "message": "", "pathname": "/home/vcap/app/app/errors.py", "lineno": 110, "exc_info": "Traceback (most recent call last):\n  File \"/home/vcap/deps/0/python/lib/python3.12/site-packages/flask/app.py\", line 917, in full_dispatch_request\n    rv = self.dispatch_request()\n         ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/vcap/deps/0/python/lib/python3.12/site-packages/flask/app.py\", line 902, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n …
=> Handle StopIteration in extract_phones when CSV files are empty/missing

run_celery.py
Tracing down some weird forking errors and instability, it sounds like we need to monkey patch gevent once when the app starts and once when celery starts.
N/A
=> monkeypatch gevent

app/__init__.py, app/celery/scheduled_tasks.py, app/job/rest.py, setup.cfg, tests/app/celery/test_scheduled_tasks.py, tests/app/clients/test_aws_cloudwatch.py, tests/app/clients/test_aws_ses.py, tests/app/delivery/test_send_to_providers.py
Because of the use of gevent and its need for monkey patching, it's necessary that all global variables that use resources be lazily initialized.  This way the monkey patching works for the whole app, and we don't get fork errors under heavy load.
In the PR we do lazy initialization of all the 'easy' global variables, which don't hit too many files.
Note:   This PR is a bit risky.  Even though I ran a bulk send test locally and it was successful, the PR might destabilize staging.  So we should push it to staging on its own and QA test it on its own, and be ready to rollback.
N/A
=> lazy initialize for gevent
